import {
  resolveCurrentChapterIndex,
  calculateRemainingBookTime,
} from '../chapterPlayback';
import type { Book, Chapter } from '@/types/Book';

jest.mock('@/constants/images', () => ({
  unknownBookImageUri: 'file:///fallback.png',
}));

jest.mock('@/constants/featureFlags', () => ({
  CLIPPED_CHAPTERS_SPIKE: true,
}));

const chapter = (
  title: string,
  startMs: number,
  chapterDuration: number,
  url = '/book.m4b',
): Chapter =>
  ({
    chapterTitle: title,
    chapterNumber: 1,
    chapterDuration,
    startMs,
    url,
    author: 'A',
    bookTitle: 'B',
    isAutoGenerated: false,
  }) as Chapter;

// Single file, real chapter offsets → clipped queue while the spike is on
const clippedChapters = [
  chapter('Ch 1', 0, 60),
  chapter('Ch 2', 60000, 60),
  chapter('Ch 3', 120000, 100),
];

// One file per chapter → always a chapter queue
const multiFileChapters = [
  chapter('Ch 1', 0, 60, '/1.mp3'),
  chapter('Ch 2', 0, 60, '/2.mp3'),
  chapter('Ch 3', 0, 100, '/3.mp3'),
];

// One file whose chapters are AUTO-generated → the gate's auto-chapter
// exclusion keeps it off the clipped path, so it is a ONE-ITEM Queue even
// with the spike on. Real offsets, so the position still names a chapter.
const autoChapters = clippedChapters.map((ch) => ({
  ...ch,
  isAutoGenerated: true,
}));

const makeBook = (chapters: Chapter[], bookDuration = 220): Book =>
  ({ bookId: 'b1', chapters, bookDuration }) as unknown as Book;

describe('resolveCurrentChapterIndex', () => {
  it('uses the queue index for clipped books, ignoring position', () => {
    expect(resolveCurrentChapterIndex(clippedChapters, 2, 0)).toBe(2);
    expect(resolveCurrentChapterIndex(clippedChapters, 1, 5000)).toBe(1);
  });

  it('uses the queue index for multi-file books', () => {
    expect(resolveCurrentChapterIndex(multiFileChapters, 1, 999)).toBe(1);
  });

  it('clamps an out-of-range queue index to the last chapter', () => {
    expect(resolveCurrentChapterIndex(clippedChapters, 99, 0)).toBe(2);
  });

  it('returns undefined when the queue index is not known yet', () => {
    expect(resolveCurrentChapterIndex(clippedChapters, undefined, 30)).toBe(
      undefined,
    );
    expect(resolveCurrentChapterIndex(clippedChapters, -1, 30)).toBe(
      undefined,
    );
  });

  it('returns undefined without chapters', () => {
    expect(resolveCurrentChapterIndex(undefined, 0, 0)).toBe(undefined);
    expect(resolveCurrentChapterIndex([], 0, 0)).toBe(undefined);
  });

  // Spike ON, but the gate rejects these chapters, so the Queue is ONE item
  // and the position is absolute. The queue index is 0 throughout and must be
  // ignored.
  it('derives the chapter from the position on a one-item Queue', () => {
    expect(resolveCurrentChapterIndex(autoChapters, 0, 0)).toBe(0);
    expect(resolveCurrentChapterIndex(autoChapters, 0, 61)).toBe(1);
    expect(resolveCurrentChapterIndex(autoChapters, 0, 130)).toBe(2);
  });
});

describe('calculateRemainingBookTime', () => {
  it('sums prior chapter durations + chapter position for clipped books', () => {
    // index 1, 30s into the chapter → played 60 + 30 = 90 of 220
    expect(calculateRemainingBookTime(makeBook(clippedChapters), 30, 1)).toBe(
      130,
    );
  });

  it('sums prior chapter durations + chapter position for multi-file books', () => {
    expect(
      calculateRemainingBookTime(makeBook(multiFileChapters), 30, 1),
    ).toBe(130);
  });

  // ⚠ MIGRATION DELTA. This used to fabricate chapter 0 and answer 190. On a
  // multi-item Queue the Queue index is the only thing that says which
  // Chapter is playing, so an unreadable one cannot be converted — and `null`
  // says so rather than reporting a Book that is barely started.
  it('declines to answer without an index on a multi-item Queue', () => {
    expect(
      calculateRemainingBookTime(makeBook(clippedChapters), 30, undefined),
    ).toBeNull();
  });

  // Best-effort by name: the unreadable chapter counts as zero, so the label
  // OVERSTATES what is left rather than going blank.
  it('counts an unusable chapter duration as zero', () => {
    const damaged = [
      chapter('Ch 1', 0, 0),
      chapter('Ch 2', 60000, 60),
      chapter('Ch 3', 120000, 100),
    ];
    expect(calculateRemainingBookTime(makeBook(damaged), 30, 2)).toBe(130);
  });

  // A one-item Queue ignores the index entirely — it can only ever be 0 —
  // so an unreadable one must NOT refuse the answer.
  it('still answers without an index on a one-item Queue', () => {
    expect(
      calculateRemainingBookTime(makeBook(autoChapters), 90, undefined),
    ).toBe(130);
  });

  it('never returns a negative remaining time', () => {
    expect(calculateRemainingBookTime(makeBook(clippedChapters), 500, 2)).toBe(
      0,
    );
  });

  it('falls back to duration - position without chapters', () => {
    expect(
      calculateRemainingBookTime(makeBook([] as Chapter[], 220), 50, 0),
    ).toBe(170);
  });
});

describe('with CLIPPED_CHAPTERS_SPIKE off (one file → a ONE-ITEM Queue)', () => {
  let legacy: typeof import('../chapterPlayback');

  beforeAll(() => {
    jest.resetModules();
    jest.doMock('@/constants/featureFlags', () => ({
      CLIPPED_CHAPTERS_SPIKE: false,
    }));
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    legacy = require('../chapterPlayback');
  });

  afterAll(() => {
    jest.dontMock('@/constants/featureFlags');
    jest.resetModules();
  });

  it('resolves the chapter from the absolute position, ignoring queue index', () => {
    expect(legacy.resolveCurrentChapterIndex(clippedChapters, 0, 0)).toBe(0);
    expect(legacy.resolveCurrentChapterIndex(clippedChapters, 0, 61)).toBe(1);
    expect(legacy.resolveCurrentChapterIndex(clippedChapters, 0, 130)).toBe(2);
  });

  it('remaining time = duration - absolute position, ignoring index', () => {
    expect(
      legacy.calculateRemainingBookTime(makeBook(clippedChapters), 90, 2),
    ).toBe(130);
  });

  it('multi-file books still use the queue index', () => {
    expect(legacy.resolveCurrentChapterIndex(multiFileChapters, 1, 999)).toBe(
      1,
    );
  });
});
