import { chapterPresentationWindow } from '@/helpers/chapterWindow';

/**
 * Rows are hand-rolled here on purpose, against the usual rule that shape
 * tests must use `support/queueShapeFixtures`. Nothing in this module asks
 * what shape a Book is — it is arithmetic over `startMs`/`chapterDuration`,
 * and the fixtures carry `url` and `isAutoGenerated` fields that would only
 * suggest this function reads them.
 */
const row = (startMs: number, chapterDuration: number) => ({
  startMs,
  chapterDuration,
});

// The device reading this whole change exists to fix: 30-minute auto
// chapters, playing "Track 05", which starts two hours in.
const autoChapters = [
  row(0, 1800),
  row(1_800_000, 1800),
  row(3_600_000, 1800),
  row(5_400_000, 1800),
  row(7_200_000, 1800),
  row(9_000_000, 1200),
];

describe('chapterPresentationWindow', () => {
  it('brackets a middle chapter by its own start and the next start', () => {
    expect(chapterPresentationWindow(autoChapters, 4)).toEqual({
      windowStartMs: 7_200_000,
      windowEndMs: 9_000_000,
    });
  });

  it('turns the measured device position into a chapter position', () => {
    // The MediaSession advertised 7203811 while Track 05 played; subtracting
    // the window is what makes the seek bar read 3.8s into a 30m chapter.
    const w = chapterPresentationWindow(autoChapters, 4)!;
    expect(7_203_811 - w.windowStartMs).toBe(3811);
    expect(w.windowEndMs - w.windowStartMs).toBe(1_800_000);
  });

  it('starts the first chapter at zero', () => {
    expect(chapterPresentationWindow(autoChapters, 0)).toEqual({
      windowStartMs: 0,
      windowEndMs: 1_800_000,
    });
  });

  it('gives the LAST chapter an explicit end from its own duration', () => {
    // ⚠ The regression this guards: an undefined end would be INHERITED from
    // the previous chapter by the native side, leaving end behind start.
    expect(chapterPresentationWindow(autoChapters, 5)).toEqual({
      windowStartMs: 9_000_000,
      windowEndMs: 10_200_000,
    });
  });

  it('prefers the next start over a chapterDuration that disagrees', () => {
    // A row whose metadata extraction failed is stored with duration 0; the
    // neighbouring starts still bracket it correctly.
    const broken = [row(0, 0), row(60_000, 0), row(120_000, 30)];
    expect(chapterPresentationWindow(broken, 0)).toEqual({
      windowStartMs: 0,
      windowEndMs: 60_000,
    });
    expect(chapterPresentationWindow(broken, 1)).toEqual({
      windowStartMs: 60_000,
      windowEndMs: 120_000,
    });
  });

  it('declines a last chapter with no usable duration', () => {
    expect(chapterPresentationWindow([row(0, 60), row(60_000, 0)], 1)).toBeNull();
  });

  it('declines rows that all sit at the same start', () => {
    // The shape that makes a backwards positional walk answer the last index
    // for every position — it has no boundaries to present.
    expect(chapterPresentationWindow([row(0, 60), row(0, 60)], 0)).toBeNull();
  });

  it('declines an out-of-range or missing index', () => {
    expect(chapterPresentationWindow(autoChapters, -1)).toBeNull();
    expect(chapterPresentationWindow(autoChapters, 99)).toBeNull();
    expect(chapterPresentationWindow(undefined, 0)).toBeNull();
    expect(chapterPresentationWindow([], 0)).toBeNull();
  });

  it('declines a single chapter with no duration rather than guessing', () => {
    expect(chapterPresentationWindow([row(0, 0)], 0)).toBeNull();
  });
});
