import {
  usesChapterQueue,
  resolveCurrentChapterIndex,
  calculateRemainingBookTime,
} from '../chapterPlayback';
import type { Book, Chapter } from '@/types/Book';

jest.mock('@/constants/images', () => ({
  unknownBookImageUri: 'file:///fallback.png',
}));

jest.mock('@/constants/featureFlags', () => ({
  CLIPPED_CHAPTERS_SPIKE: true,
}));

const chapter = (
  title: string,
  startMs: number,
  chapterDuration: number,
  url = '/book.m4b',
): Chapter =>
  ({
    chapterTitle: title,
    chapterNumber: 1,
    chapterDuration,
    startMs,
    url,
    author: 'A',
    bookTitle: 'B',
    isAutoGenerated: false,
  }) as Chapter;

// Single file, real chapter offsets → clipped queue while the spike is on
const clippedChapters = [
  chapter('Ch 1', 0, 60),
  chapter('Ch 2', 60000, 60),
  chapter('Ch 3', 120000, 100),
];

// One file per chapter → always a chapter queue
const multiFileChapters = [
  chapter('Ch 1', 0, 60, '/1.mp3'),
  chapter('Ch 2', 0, 60, '/2.mp3'),
  chapter('Ch 3', 0, 100, '/3.mp3'),
];

// Single file with no usable offsets → loads as ONE queue item even with
// the spike on (shouldUseClippedChapters is false without valid data)
const noOffsetChapters = [
  chapter('Ch 1', 0, 60),
  chapter('Ch 2', 0, 60),
];

const makeBook = (chapters: Chapter[], bookDuration = 220): Book =>
  ({ bookId: 'b1', chapters, bookDuration }) as unknown as Book;

describe('usesChapterQueue', () => {
  it('is true for clipped single-file books (spike on, valid offsets)', () => {
    expect(usesChapterQueue(clippedChapters)).toBe(true);
  });

  it('is true for multi-file books', () => {
    expect(usesChapterQueue(multiFileChapters)).toBe(true);
  });

  it('is false for single-file books without valid offsets (one queue item)', () => {
    expect(usesChapterQueue(noOffsetChapters)).toBe(false);
  });

  it('is false for single-file books with auto-generated chapters (legacy path)', () => {
    const autoChapters = clippedChapters.map((ch) => ({
      ...ch,
      isAutoGenerated: true,
    }));
    expect(usesChapterQueue(autoChapters)).toBe(false);
  });
});

describe('resolveCurrentChapterIndex', () => {
  it('uses the queue index for clipped books, ignoring position', () => {
    expect(resolveCurrentChapterIndex(clippedChapters, 2, 0)).toBe(2);
    expect(resolveCurrentChapterIndex(clippedChapters, 1, 5000)).toBe(1);
  });

  it('uses the queue index for multi-file books', () => {
    expect(resolveCurrentChapterIndex(multiFileChapters, 1, 999)).toBe(1);
  });

  it('clamps an out-of-range queue index to the last chapter', () => {
    expect(resolveCurrentChapterIndex(clippedChapters, 99, 0)).toBe(2);
  });

  it('returns undefined when the queue index is not known yet', () => {
    expect(resolveCurrentChapterIndex(clippedChapters, undefined, 30)).toBe(
      undefined,
    );
    expect(resolveCurrentChapterIndex(clippedChapters, -1, 30)).toBe(
      undefined,
    );
  });

  it('returns undefined without chapters', () => {
    expect(resolveCurrentChapterIndex(undefined, 0, 0)).toBe(undefined);
    expect(resolveCurrentChapterIndex([], 0, 0)).toBe(undefined);
  });
});

describe('calculateRemainingBookTime', () => {
  it('sums prior chapter durations + chapter position for clipped books', () => {
    // index 1, 30s into the chapter → played 60 + 30 = 90 of 220
    expect(calculateRemainingBookTime(makeBook(clippedChapters), 30, 1)).toBe(
      130,
    );
  });

  it('sums prior chapter durations + chapter position for multi-file books', () => {
    expect(
      calculateRemainingBookTime(makeBook(multiFileChapters), 30, 1),
    ).toBe(130);
  });

  it('treats a missing index as chapter 0 in chapter-queue mode', () => {
    expect(
      calculateRemainingBookTime(makeBook(clippedChapters), 30, undefined),
    ).toBe(190);
  });

  it('never returns a negative remaining time', () => {
    expect(calculateRemainingBookTime(makeBook(clippedChapters), 500, 2)).toBe(
      0,
    );
  });

  it('falls back to duration - position without chapters', () => {
    expect(
      calculateRemainingBookTime(makeBook([] as Chapter[], 220), 50, 0),
    ).toBe(170);
  });
});

describe('with CLIPPED_CHAPTERS_SPIKE off (legacy single-file mode)', () => {
  let legacy: typeof import('../chapterPlayback');

  beforeAll(() => {
    jest.resetModules();
    jest.doMock('@/constants/featureFlags', () => ({
      CLIPPED_CHAPTERS_SPIKE: false,
    }));
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    legacy = require('../chapterPlayback');
  });

  afterAll(() => {
    jest.dontMock('@/constants/featureFlags');
    jest.resetModules();
  });

  it('single-file books with offsets are NOT a chapter queue', () => {
    expect(legacy.usesChapterQueue(clippedChapters)).toBe(false);
  });

  it('resolves the chapter from the absolute position, ignoring queue index', () => {
    expect(legacy.resolveCurrentChapterIndex(clippedChapters, 0, 0)).toBe(0);
    expect(legacy.resolveCurrentChapterIndex(clippedChapters, 0, 61)).toBe(1);
    expect(legacy.resolveCurrentChapterIndex(clippedChapters, 0, 130)).toBe(2);
  });

  it('remaining time = duration - absolute position, ignoring index', () => {
    expect(
      legacy.calculateRemainingBookTime(makeBook(clippedChapters), 90, 2),
    ).toBe(130);
  });

  it('multi-file books still use the queue index', () => {
    expect(legacy.usesChapterQueue(multiFileChapters)).toBe(true);
    expect(legacy.resolveCurrentChapterIndex(multiFileChapters, 1, 999)).toBe(
      1,
    );
  });
});
