import {
  buildClippedChapterTracks,
  shouldUseClippedChapters,
  estimateClippedTransitionPeakBytes,
} from '../clippedChapters';
import { getHeapLimitBytes } from '@/helpers/deviceHeap';
import type { Book, Chapter } from '@/types/Book';

jest.mock('@/constants/featureFlags', () => ({
  CLIPPED_CHAPTERS_SPIKE: true,
}));

jest.mock('@/helpers/deviceHeap', () => ({
  getHeapLimitBytes: jest.fn(() => 512 * 1024 * 1024),
}));

const mockHeapLimit = getHeapLimitBytes as jest.Mock;

const chapter = (
  title: string,
  startMs: number,
  chapterDuration: number,
  url = '/book.m4b',
): Chapter =>
  ({
    chapterTitle: title,
    chapterNumber: 1,
    chapterDuration,
    startMs,
    url,
    author: 'A',
    bookTitle: 'B',
    isAutoGenerated: false,
  }) as Chapter;

const singleFileBook = {
  bookId: 'b1',
  bookTitle: 'Dune',
  author: 'Frank Herbert',
  artwork: 'file:///art.webp',
  chapters: [
    chapter('Ch 1', 0, 60),
    chapter('Ch 2', 60000, 60),
    chapter('Ch 3', 120000, 100),
  ],
} as unknown as Book;

describe('shouldUseClippedChapters', () => {
  it('is true for a single-file book with valid chapter data', () => {
    expect(shouldUseClippedChapters(singleFileBook.chapters)).toBe(true);
  });

  it('is false for multi-file books (chapters have distinct urls)', () => {
    const chapters = [
      chapter('Ch 1', 0, 60, '/1.mp3'),
      chapter('Ch 2', 0, 60, '/2.mp3'),
    ];
    expect(shouldUseClippedChapters(chapters)).toBe(false);
  });

  it('is false without valid chapter start data (all startMs 0)', () => {
    const chapters = [chapter('Ch 1', 0, 60), chapter('Ch 2', 0, 60)];
    expect(shouldUseClippedChapters(chapters)).toBe(false);
  });

  it('is false for undefined or single-chapter lists', () => {
    expect(shouldUseClippedChapters(undefined)).toBe(false);
    expect(shouldUseClippedChapters([chapter('Only', 0, 60)])).toBe(false);
  });

  it('is false for auto-generated chapters (synthetic offsets seek inexactly)', () => {
    const autoChapters = singleFileBook.chapters!.map((ch) => ({
      ...ch,
      isAutoGenerated: true,
    }));
    expect(shouldUseClippedChapters(autoChapters)).toBe(false);
  });

  it('treats a missing isAutoGenerated flag as real chapter data', () => {
    const withoutFlag = singleFileBook.chapters!.map(
      ({ isAutoGenerated: _omitted, ...rest }) => rest,
    );
    expect(shouldUseClippedChapters(withoutFlag as Chapter[])).toBe(true);
  });
});

/**
 * Memory gate: each clipped queue item is its own ProgressiveMediaSource, and
 * ExoPlayer's Mp4Extractor materializes the full sample table (~24 B per AAC
 * frame) per prepared period. At a chapter transition two periods coexist, so
 * an oversized book OOMs at every chapter boundary (device-verified with a
 * 28.7 h 44.1 kHz m4b on a 256 MiB heap). Such books must fall back to the
 * legacy single-track path.
 */
describe('shouldUseClippedChapters memory gate', () => {
  // Builds a single-file book whose chapters sum to `hours` of audio.
  const longBook = (hours: number): Chapter[] => {
    const half = (hours * 3600) / 2;
    return [chapter('Ch 1', 0, half), chapter('Ch 2', half * 1000, half)];
  };

  beforeEach(() => {
    mockHeapLimit.mockReturnValue(512 * 1024 * 1024);
  });

  it('keeps a ~29h book (Book 7 case) clipped on a 512 MiB heap', () => {
    expect(shouldUseClippedChapters(longBook(29))).toBe(true);
  });

  it('falls back to legacy single-track for a 40h book on a 512 MiB heap', () => {
    expect(shouldUseClippedChapters(longBook(40))).toBe(false);
  });

  it('falls back for a ~29h book on a 256 MiB heap (no largeHeap)', () => {
    mockHeapLimit.mockReturnValue(256 * 1024 * 1024);
    expect(shouldUseClippedChapters(longBook(29))).toBe(false);
  });

  it('estimates peak bytes proportionally to total chapter duration', () => {
    const oneHour = estimateClippedTransitionPeakBytes(longBook(1));
    const twoHours = estimateClippedTransitionPeakBytes(longBook(2));
    expect(twoHours).toBeCloseTo(oneHour * 2, 0);
  });

  it('estimates the device-verified Book 7 case (28.68h) at ~213 MB', () => {
    // 103,238 s of 44.1 kHz AAC measured at ~107 MB of sample tables per
    // period on device; the transition peak is two periods.
    const estimate = estimateClippedTransitionPeakBytes([
      chapter('Ch 1', 0, 51619),
      chapter('Ch 2', 51_619_000, 51619),
    ]);
    expect(estimate).toBeGreaterThan(200 * 1024 * 1024);
    expect(estimate).toBeLessThan(230 * 1024 * 1024);
  });
});

describe('buildClippedChapterTracks', () => {
  it('builds one track per chapter, all pointing at the same file', () => {
    const tracks = buildClippedChapterTracks(singleFileBook);

    expect(tracks).toHaveLength(3);
    expect(tracks.every((t) => t.url === '/book.m4b')).toBe(true);
    expect(tracks.map((t) => t.title)).toEqual(['Ch 1', 'Ch 2', 'Ch 3']);
  });

  it('sets clip windows: start = chapter startMs, end = next chapter startMs', () => {
    const tracks = buildClippedChapterTracks(singleFileBook);

    expect(tracks[0].clipStartMs).toBe(0);
    expect(tracks[0].clipEndMs).toBe(60000);
    expect(tracks[1].clipStartMs).toBe(60000);
    expect(tracks[1].clipEndMs).toBe(120000);
    // Last chapter runs to end of source
    expect(tracks[2].clipStartMs).toBe(120000);
    expect(tracks[2].clipEndMs).toBeUndefined();
  });

  it('carries book metadata and per-chapter duration onto each track', () => {
    const tracks = buildClippedChapterTracks(singleFileBook);

    expect(tracks[1]).toMatchObject({
      artist: 'Frank Herbert',
      album: 'Dune',
      bookId: 'b1',
      artwork: 'file:///art.webp',
      duration: 60,
    });
  });

  it('gives each track a distinct mediaId', () => {
    const tracks = buildClippedChapterTracks(singleFileBook);
    const ids = new Set(tracks.map((t) => t.mediaId));
    expect(ids.size).toBe(3);
  });

  // Artwork falls through to undefined so the native side can substitute the
  // bundled default (MusicService.applyDefaultArtwork); no JS route to the
  // bundled image survives a release build.
  it('leaves artwork undefined when the book has none', () => {
    const book = { ...singleFileBook, artwork: null } as unknown as Book;
    const tracks = buildClippedChapterTracks(book);
    expect(tracks[0].artwork).toBeUndefined();
  });

  it('drops a persisted schemeless placeholder so native can substitute', () => {
    // usePopulateDatabase stores resolveAssetSource's output for coverless
    // books; in release that is a schemeless resource id Coil cannot load.
    const book = {
      ...singleFileBook,
      artwork: 'src_assets_images_unknown_track',
    } as unknown as Book;
    const tracks = buildClippedChapterTracks(book);
    expect(tracks[0].artwork).toBeUndefined();
  });

  it('leaves a real cover URI untouched', () => {
    const book = {
      ...singleFileBook,
      artwork: 'file:///data/artwork/real-cover.png',
    } as unknown as Book;
    const tracks = buildClippedChapterTracks(book);
    expect(tracks[0].artwork).toBe('file:///data/artwork/real-cover.png');
  });
});
