import {
  buildClippedChapterTracks,
  shouldUseClippedChapters,
} from '../clippedChapters';
import type { Book, Chapter } from '@/types/Book';

jest.mock('@/constants/images', () => ({
  unknownBookImageUri: 'file:///fallback.png',
}));

jest.mock('@/constants/featureFlags', () => ({
  CLIPPED_CHAPTERS_SPIKE: true,
}));

const chapter = (
  title: string,
  startMs: number,
  chapterDuration: number,
  url = '/book.m4b',
): Chapter =>
  ({
    chapterTitle: title,
    chapterNumber: 1,
    chapterDuration,
    startMs,
    url,
    author: 'A',
    bookTitle: 'B',
    isAutoGenerated: false,
  }) as Chapter;

const singleFileBook = {
  bookId: 'b1',
  bookTitle: 'Dune',
  author: 'Frank Herbert',
  artwork: 'file:///art.webp',
  chapters: [
    chapter('Ch 1', 0, 60),
    chapter('Ch 2', 60000, 60),
    chapter('Ch 3', 120000, 100),
  ],
} as unknown as Book;

describe('shouldUseClippedChapters', () => {
  it('is true for a single-file book with valid chapter data', () => {
    expect(shouldUseClippedChapters(singleFileBook.chapters)).toBe(true);
  });

  it('is false for multi-file books (chapters have distinct urls)', () => {
    const chapters = [
      chapter('Ch 1', 0, 60, '/1.mp3'),
      chapter('Ch 2', 0, 60, '/2.mp3'),
    ];
    expect(shouldUseClippedChapters(chapters)).toBe(false);
  });

  it('is false without valid chapter start data (all startMs 0)', () => {
    const chapters = [chapter('Ch 1', 0, 60), chapter('Ch 2', 0, 60)];
    expect(shouldUseClippedChapters(chapters)).toBe(false);
  });

  it('is false for undefined or single-chapter lists', () => {
    expect(shouldUseClippedChapters(undefined)).toBe(false);
    expect(shouldUseClippedChapters([chapter('Only', 0, 60)])).toBe(false);
  });
});

describe('buildClippedChapterTracks', () => {
  it('builds one track per chapter, all pointing at the same file', () => {
    const tracks = buildClippedChapterTracks(singleFileBook);

    expect(tracks).toHaveLength(3);
    expect(tracks.every((t) => t.url === '/book.m4b')).toBe(true);
    expect(tracks.map((t) => t.title)).toEqual(['Ch 1', 'Ch 2', 'Ch 3']);
  });

  it('sets clip windows: start = chapter startMs, end = next chapter startMs', () => {
    const tracks = buildClippedChapterTracks(singleFileBook);

    expect(tracks[0].clipStartMs).toBe(0);
    expect(tracks[0].clipEndMs).toBe(60000);
    expect(tracks[1].clipStartMs).toBe(60000);
    expect(tracks[1].clipEndMs).toBe(120000);
    // Last chapter runs to end of source
    expect(tracks[2].clipStartMs).toBe(120000);
    expect(tracks[2].clipEndMs).toBeUndefined();
  });

  it('carries book metadata and per-chapter duration onto each track', () => {
    const tracks = buildClippedChapterTracks(singleFileBook);

    expect(tracks[1]).toMatchObject({
      artist: 'Frank Herbert',
      album: 'Dune',
      bookId: 'b1',
      artwork: 'file:///art.webp',
      duration: 60,
    });
  });

  it('gives each track a distinct mediaId', () => {
    const tracks = buildClippedChapterTracks(singleFileBook);
    const ids = new Set(tracks.map((t) => t.mediaId));
    expect(ids.size).toBe(3);
  });

  it('falls back to the unknown-book artwork when the book has none', () => {
    const book = { ...singleFileBook, artwork: null } as unknown as Book;
    const tracks = buildClippedChapterTracks(book);
    expect(tracks[0].artwork).toBe('file:///fallback.png');
  });
});
