import { queueShapeOf } from '../queueShape';
import { getHeapLimitBytes } from '@/helpers/deviceHeap';
import type { Chapter } from '@/types/Book';

jest.mock('@/constants/featureFlags', () => ({
  CLIPPED_CHAPTERS_SPIKE: true,
}));

jest.mock('@/helpers/deviceHeap', () => ({
  getHeapLimitBytes: jest.fn(() => 512 * 1024 * 1024),
}));

const mockHeapLimit = getHeapLimitBytes as jest.Mock;

/**
 * Named fields on purpose. `clippedChapters.test.ts` has a positional factory
 * of the same shape but a DIFFERENT parameter order; two positional factories
 * that disagree is a trap that type-checks, so this one refuses to be
 * confusable with it.
 */
const chapter = (fields: {
  startMs: number;
  duration: number;
  url: string;
  auto?: boolean;
}): Chapter =>
  ({
    chapterTitle: 'Ch',
    chapterNumber: 1,
    chapterDuration: fields.duration,
    startMs: fields.startMs,
    url: fields.url,
    author: 'A',
    bookTitle: 'B',
    isAutoGenerated: fields.auto ?? false,
  }) as Chapter;

beforeEach(() => {
  mockHeapLimit.mockReturnValue(512 * 1024 * 1024);
});

/**
 * The four authoring shapes from `.scratch/queue-shape/spec.md`. Shape D is
 * pinned to what it CURRENTLY answers, not to what it should answer: it is
 * already broken in the queue builder (one whole-file track per chapter row)
 * and the spec deliberately refuses to represent it. Pinning it here is what
 * stops a later ticket moving it silently.
 */
describe('queueShapeOf — the four authoring shapes', () => {
  it('A. multi-file, one chapter per file → multi-item', () => {
    const chapters = [
      chapter({ startMs: 0, duration: 600, url: '/01.mp3' }),
      chapter({ startMs: 0, duration: 600, url: '/02.mp3' }),
      chapter({ startMs: 0, duration: 600, url: '/03.mp3' }),
    ];
    expect(queueShapeOf(chapters)).toBe('multi-item');
  });

  it('B. single-file with real chapters, under the heap budget → multi-item (clipped)', () => {
    const chapters = [
      chapter({ startMs: 0, duration: 600, url: '/book.m4b' }),
      chapter({ startMs: 600_000, duration: 600, url: '/book.m4b' }),
      chapter({ startMs: 1_200_000, duration: 600, url: '/book.m4b' }),
    ];
    expect(queueShapeOf(chapters)).toBe('multi-item');
  });

  it('B. single-file with real chapters, over the heap budget → one-item (legacy)', () => {
    mockHeapLimit.mockReturnValue(1024);
    const chapters = [
      chapter({ startMs: 0, duration: 600, url: '/book.m4b' }),
      chapter({ startMs: 600_000, duration: 600, url: '/book.m4b' }),
    ];
    expect(queueShapeOf(chapters)).toBe('one-item');
  });

  it('B. single-file whose chapters are auto-generated → one-item (legacy)', () => {
    const chapters = [
      chapter({ startMs: 0, duration: 600, url: '/book.mp3', auto: true }),
      chapter({ startMs: 600_000, duration: 600, url: '/book.mp3', auto: true }),
    ];
    expect(queueShapeOf(chapters)).toBe('one-item');
  });

  it('C. single-file with no chapter metadata → one-item', () => {
    const chapters = [chapter({ startMs: 0, duration: 3600, url: '/book.m4b' })];
    expect(queueShapeOf(chapters)).toBe('one-item');
  });

  it('D. multi-file, each file with embedded chapters → multi-item', () => {
    const chapters = [
      chapter({ startMs: 0, duration: 300, url: '/01.m4b' }),
      chapter({ startMs: 300_000, duration: 300, url: '/01.m4b' }),
      chapter({ startMs: 0, duration: 300, url: '/02.m4b' }),
      chapter({ startMs: 300_000, duration: 300, url: '/02.m4b' }),
    ];
    expect(queueShapeOf(chapters)).toBe('multi-item');
  });
});

/**
 * The gate's remaining exclusion, which the four-shapes block above does not
 * reach: shape B covers a Book the heap rejects and one the auto-chapter rule
 * rejects, but not one rejected for having no offsets to cut at. This used to
 * be pinned through the deleted `usesChapterQueue`; without it, that exclusion
 * has no test.
 */
describe('queueShapeOf — one file with no usable chapter offsets', () => {
  it('several chapters, one file, every startMs 0 → one-item', () => {
    // Several chapters, one file, every startMs 0: `hasValidChapterData` is
    // false, so there is nothing to clip against and the whole Book is one
    // queue item. ⚠ Not the same case as shape C — this Book HAS several
    // chapters, it just has no offsets to cut them at.
    expect(
      queueShapeOf([
        chapter({ startMs: 0, duration: 60, url: '/book.m4b' }),
        chapter({ startMs: 0, duration: 60, url: '/book.m4b' }),
      ]),
    ).toBe('one-item');
  });
});

describe('queueShapeOf — the one-chapter correction', () => {
  it('answers one-item for a book with exactly one chapter', () => {
    expect(queueShapeOf([chapter({ startMs: 0, duration: 3600, url: '/book.m4b' })])).toBe('one-item');
  });

  it('answers one-item for a single chapter even with a non-zero startMs', () => {
    expect(queueShapeOf([chapter({ startMs: 5000, duration: 3600, url: '/book.m4b' })])).toBe('one-item');
  });
});

describe('queueShapeOf — undecidable inputs fail closed', () => {
  it('answers multi-item for undefined chapters', () => {
    expect(queueShapeOf(undefined)).toBe('multi-item');
  });

  it('answers multi-item for an empty chapter array', () => {
    expect(queueShapeOf([])).toBe('multi-item');
  });
});

/**
 * The spike is `queueShapeOf`'s only non-chapter input besides the heap
 * limit, and flipping it off is the supported way back to the classic
 * single-track behaviour. This coverage used to live on `usesChapterQueue`
 * in `chapterPlayback.test.ts`; that predicate is gone, and the question is
 * this module's.
 */
describe('queueShapeOf — with CLIPPED_CHAPTERS_SPIKE off', () => {
  let legacy: typeof import('../queueShape');

  beforeAll(() => {
    jest.resetModules();
    jest.doMock('@/constants/featureFlags', () => ({
      CLIPPED_CHAPTERS_SPIKE: false,
    }));
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    legacy = require('../queueShape');
  });

  afterAll(() => {
    jest.dontMock('@/constants/featureFlags');
    jest.resetModules();
  });

  it('B. one file with real chapters → one-item, whatever the heap allows', () => {
    expect(
      legacy.queueShapeOf([
        chapter({ startMs: 0, duration: 60, url: '/book.m4b' }),
        chapter({ startMs: 60000, duration: 60, url: '/book.m4b' }),
      ]),
    ).toBe('one-item');
  });

  it('A. one file per chapter → still multi-item', () => {
    expect(
      legacy.queueShapeOf([
        chapter({ startMs: 0, duration: 60, url: '/1.mp3' }),
        chapter({ startMs: 0, duration: 60, url: '/2.mp3' }),
      ]),
    ).toBe('multi-item');
  });
});

describe('queueShapeOf — memoisation', () => {
  it('returns the same verdict for the same array reference', () => {
    const chapters = [chapter({ startMs: 0, duration: 3600, url: '/book.m4b' })];
    expect(queueShapeOf(chapters)).toBe('one-item');
    expect(queueShapeOf(chapters)).toBe('one-item');
  });

  it('does not consult the heap gate again for a cached array', () => {
    const chapters = [
      chapter({ startMs: 0, duration: 600, url: '/book.m4b' }),
      chapter({ startMs: 600_000, duration: 600, url: '/book.m4b' }),
    ];
    expect(queueShapeOf(chapters)).toBe('multi-item');
    const callsAfterFirst = mockHeapLimit.mock.calls.length;
    expect(queueShapeOf(chapters)).toBe('multi-item');
    expect(mockHeapLimit.mock.calls.length).toBe(callsAfterFirst);
  });

  it('re-derives for a fresh array with the same contents (rescan)', () => {
    const before = [
      chapter({ startMs: 0, duration: 600, url: '/book.m4b' }),
      chapter({ startMs: 600_000, duration: 600, url: '/book.m4b' }),
    ];
    expect(queueShapeOf(before)).toBe('multi-item');

    mockHeapLimit.mockReturnValue(1024);
    const after = [
      chapter({ startMs: 0, duration: 600, url: '/book.m4b' }),
      chapter({ startMs: 600_000, duration: 600, url: '/book.m4b' }),
    ];
    expect(queueShapeOf(after)).toBe('one-item');
  });
});
