import { remainingChapterCount } from '../remainingChapterCount';
import { useLibraryStore } from '@/store/library';
import { createFakePlayer, type FakePlayer } from './support/fakePlayer';
import {
  oneItemChapters,
  multiItemChapters,
} from './support/queueShapeFixtures';

/*
 * The stepper's ceiling, driven through the fake player so the real adapter
 * runs on top of it. Every case here was a branch that existed twice — once in
 * `timer.tsx`, once in `SleepTimerOptions.tsx` — before the unit landed.
 *
 * ⚠ THE FIXTURES CARRY REAL CHAPTER ROWS, and they have to. This unit used to
 * read `queue.length === 1` for the Queue shape, so its fixtures could leave
 * `url`, `chapterDuration` and `isAutoGenerated` off and let the fake player's
 * queue decide. It now asks `queueShapeOf`, which reads exactly those fields —
 * see `support/queueShapeFixtures.ts` for why a row carrying only `startMs`
 * answers 'multi-item'.
 */

let mockPlayer: FakePlayer;

jest.mock('react-native-track-player', () => ({
  __esModule: true,
  default: {
    getQueue: (...a: unknown[]) => mockPlayer.api.getQueue(...a),
    getProgress: (...a: unknown[]) => mockPlayer.api.getProgress(...a),
    getActiveTrack: (...a: unknown[]) => mockPlayer.api.getActiveTrack(...a),
    getActiveTrackIndex: (...a: unknown[]) =>
      mockPlayer.api.getActiveTrackIndex(...a),
  },
}));

// The store imports WatermelonDB's SQLite adapter, unresolvable in the node
// lane. Every branch now reads it — the chapter list is what the count is
// taken from — so each test sets the book it is about.
jest.mock('@/store/library', () => ({
  useLibraryStore: { getState: jest.fn(() => ({ books: {} })) },
}));

const mockGetState = useLibraryStore.getState as jest.Mock;

// Chapters at 0:00, 10:00, 20:00, 30:00 — four boundaries, three left from
// the first.
const oneItem = oneItemChapters([0, 600_000, 1_200_000, 1_800_000]);

const storeWith = (chapters: unknown[]) => ({
  books: { 'book-1': { chapters } },
});

beforeEach(() => {
  jest.clearAllMocks();
  mockGetState.mockReturnValue({ books: {} });
});

describe('remainingChapterCount — multi-file book', () => {
  it('counts the chapters after the active queue item', async () => {
    mockPlayer = createFakePlayer({
      durations: [600, 600, 600, 600],
      index: 1,
      position: 0,
    });
    mockGetState.mockReturnValue(storeWith(multiItemChapters(4)));

    expect(await remainingChapterCount()).toBe(2);
  });

  it('is 0 on the last queue item', async () => {
    mockPlayer = createFakePlayer({
      durations: [600, 600, 600],
      index: 2,
      position: 0,
    });
    mockGetState.mockReturnValue(storeWith(multiItemChapters(3)));

    expect(await remainingChapterCount()).toBe(0);
  });

  it('is 0 when the active queue index cannot be read', async () => {
    mockPlayer = createFakePlayer({
      durations: [600, 600, 600],
      index: 0,
      position: 0,
    });
    mockPlayer.api.getActiveTrackIndex.mockResolvedValue(undefined);
    mockGetState.mockReturnValue(storeWith(multiItemChapters(3)));

    expect(await remainingChapterCount()).toBe(0);
  });
});

describe('remainingChapterCount — legacy single-file book', () => {
  it('counts the chapter boundaries after the playhead', async () => {
    // 1250s is inside chapter 3 (index 2), so one boundary is left.
    mockPlayer = createFakePlayer({
      durations: [3600],
      index: 0,
      position: 1250,
    });
    mockGetState.mockReturnValue(storeWith(oneItem));

    expect(await remainingChapterCount()).toBe(1);
  });

  it('counts from the start of the book', async () => {
    mockPlayer = createFakePlayer({ durations: [3600], index: 0, position: 0 });
    mockGetState.mockReturnValue(storeWith(oneItem));

    expect(await remainingChapterCount()).toBe(3);
  });

  it('is 0 when the book has no usable chapters', async () => {
    mockPlayer = createFakePlayer({ durations: [3600], index: 0, position: 0 });
    mockGetState.mockReturnValue(storeWith([oneItem[0]]));

    expect(await remainingChapterCount()).toBe(0);
  });

  it('is 0 when the book is not in the library store', async () => {
    mockPlayer = createFakePlayer({ durations: [3600], index: 0, position: 0 });

    expect(await remainingChapterCount()).toBe(0);
  });
});

describe('remainingChapterCount — the Queue is never read', () => {
  it('answers without marshalling the track list across the bridge', async () => {
    mockPlayer = createFakePlayer({
      durations: [600, 600, 600, 600],
      index: 1,
      position: 0,
    });
    mockGetState.mockReturnValue(storeWith(multiItemChapters(4)));

    await remainingChapterCount();

    expect(mockPlayer.api.getQueue).not.toHaveBeenCalled();
  });
});

describe('remainingChapterCount — the ceiling is not known', () => {
  it('is null with no Book loaded (empty queue)', async () => {
    mockPlayer = createFakePlayer({ durations: [], index: 0, position: 0 });

    expect(await remainingChapterCount()).toBeNull();
  });

  it('is null when the active item carries no bookId', async () => {
    mockPlayer = createFakePlayer({
      durations: [3600],
      index: 0,
      position: 0,
    });
    mockPlayer.api.getActiveTrack.mockResolvedValue({});
    mockGetState.mockReturnValue(storeWith(oneItem));

    expect(await remainingChapterCount()).toBeNull();
  });

  it('is null when a Player read throws', async () => {
    mockPlayer = createFakePlayer({
      durations: [600, 600],
      index: 0,
      position: 0,
    });
    mockPlayer.api.getActiveTrack.mockRejectedValue(new Error('no player'));

    expect(await remainingChapterCount()).toBeNull();
  });

  it('is null when a later read throws mid-computation', async () => {
    mockPlayer = createFakePlayer({
      durations: [3600],
      index: 0,
      position: 0,
    });
    mockPlayer.api.getProgress.mockRejectedValue(new Error('no player'));
    mockGetState.mockReturnValue(storeWith(oneItem));

    expect(await remainingChapterCount()).toBeNull();
  });
});
