import { Author, Book, Chapter } from '@/types/Book';
import { create, StoreApi, UseBoundStore } from 'zustand';
// import { combine } from 'zustand/middleware';
// import { useCallback } from 'react';
import database from '@/db';
import { useShallow } from 'zustand/shallow';
import { Subscription } from 'rxjs';
// import AuthorModel from '@/db/models/Author';
import BookModel from '@/db/models/Book';
import ChapterModel from '@/db/models/Chapter';
// import { Q } from '@nozbe/watermelondb';
import { scheduleAndroidAutoCacheWrite } from '@/helpers/androidAutoCache';

/**
 * Using a mapped type for books allows for O(1) lookup time, which is much more
 * performant than iterating through a large array to find a book by its ID.
 */
type BookMap = Record<string, Book>;

interface LibraryState {
  authors: Author[];
  books: BookMap; // New: Normalized book data for efficient lookups.
  setAuthors: (authors: Author[]) => void;
  // getAuthors is removed as direct access is less safe. Selectors are preferred.
  playbackProgress: Record<string, number>; // New: Stores real-time playback progress
  playbackIndex: Record<string, number>; // New: Stores real-time playback progress

  setPlaybackProgress: (bookId: string, progress: number) => void;
  setPlaybackIndex: (bookId: string, index: number) => void;
  getPlaybackProgress: (bookId: string) => number;
  getPlaybackIndex: (bookId: string) => number;
  init: () => () => void; // Function to initialize and return cleanup
  refresh: () => Promise<void>; // Force re-fetch from database
  updateBookChapterIndex: (
    bookId: string,
    chapterIndex: number,
  ) => Promise<void>;
  _cleanup?: () => void; // Internal: tracks active subscription cleanup
}

// Author foreign keys of converted books, kept for the observer's change
// detection (Book stores the author *name*, so author_id needs its own cache).
const bookAuthorIdCache = new Map<string, string>();

/** Converts a WatermelonDB BookModel (plus its relations) to the store's Book shape. */
async function convertBookModelToBook(bookModel: BookModel): Promise<Book> {
  const authorModel = await (bookModel.author as any).fetch();
  const chapterModels = await (bookModel.chapters as any).fetch();

  const chaptersData: Chapter[] = chapterModels
    .map((chapter: ChapterModel) => ({
      author: authorModel?.name ?? 'Unknown Author',
      bookTitle: bookModel.title,
      chapterTitle: chapter.title,
      chapterNumber: chapter.chapterNumber,
      chapterDuration: chapter.chapterDuration,
      startMs: chapter.startMs,
      url: chapter.url,
      isAutoGenerated: chapter.isAutoGenerated || false,
    }))
    .sort((a: Chapter, b: Chapter) => (a.startMs ?? 0) - (b.startMs ?? 0));

  const bookData: Book = {
    bookId: bookModel.id,
    author: authorModel?.name ?? 'Unknown Author',
    bookTitle: bookModel.title,
    chapters: chaptersData,
    artwork: bookModel.artwork,
    artworkHeight: bookModel.artworkHeight,
    artworkWidth: bookModel.artworkWidth,
    artworkColors: {
      dominantAndroid: bookModel.coverColorDominant,
      vibrant: bookModel.coverColorVibrant,
      darkVibrant: bookModel.coverColorDarkVibrant,
      lightVibrant: bookModel.coverColorLightVibrant,
      muted: bookModel.coverColorMuted,
      darkMuted: bookModel.coverColorDarkMuted,
      lightMuted: bookModel.coverColorLightMuted,
    },
    selectedAccentColorType: bookModel.selectedAccentColorType ?? null,
    bookDuration: bookModel.bookDuration,
    bookProgress: {
      currentChapterIndex: bookModel.currentChapterIndex,
      currentChapterProgress: bookModel.currentChapterProgress,
    },
    bookProgressValue: bookModel.bookProgressValue,
    lastPlayedAt: bookModel.lastPlayedAt?.getTime() ?? null,
    finishedAt: bookModel.finishedAt?.getTime() ?? null,
    hasAutoGeneratedChapters: bookModel.hasAutoGeneratedChapters || false,
    isSingleFile: bookModel.isSingleFile ?? false,
    metadata: {
      year: bookModel.year?.toString(),
      description: bookModel.description,
      narrator: bookModel.narrator,
      genre: bookModel.genre,
      sampleRate: bookModel.sampleRate,
      bitrate: bookModel.bitrate,
      codec: bookModel.codec,
      copyright: bookModel.copyright,
      totalTrackCount: bookModel.totalTrackCount,
      ctime: bookModel.createdAt,
      mtime: bookModel.updatedAt,
    },
  };

  // Relation .id reads the foreign key without fetching the record
  bookAuthorIdCache.set(bookModel.id, (bookModel.author as any).id);
  return bookData;
}

/**
 * True when every column observed by the library subscription still matches
 * the cached Book, so re-conversion (two relation fetches + rebuild) can be
 * skipped. observeWithColumns emits ALL matching records on every change;
 * without this check one book's edit re-fetches the whole library.
 * MUST be kept in sync with the observeWithColumns column list in init().
 */
function isCachedBookCurrent(cached: Book, bookModel: BookModel): boolean {
  return (
    bookAuthorIdCache.get(bookModel.id) === (bookModel.author as any).id &&
    cached.bookTitle === bookModel.title &&
    cached.bookProgressValue === bookModel.bookProgressValue &&
    cached.lastPlayedAt === (bookModel.lastPlayedAt?.getTime() ?? null) &&
    cached.finishedAt === (bookModel.finishedAt?.getTime() ?? null) &&
    cached.artwork === bookModel.artwork &&
    cached.artworkHeight === bookModel.artworkHeight &&
    cached.artworkWidth === bookModel.artworkWidth &&
    (cached.selectedAccentColorType ?? null) ===
      (bookModel.selectedAccentColorType ?? null) &&
    cached.artworkColors?.dominantAndroid === bookModel.coverColorDominant &&
    cached.artworkColors?.vibrant === bookModel.coverColorVibrant &&
    cached.artworkColors?.darkVibrant === bookModel.coverColorDarkVibrant &&
    cached.artworkColors?.lightVibrant === bookModel.coverColorLightVibrant &&
    cached.artworkColors?.muted === bookModel.coverColorMuted &&
    cached.artworkColors?.darkMuted === bookModel.coverColorDarkMuted &&
    cached.artworkColors?.lightMuted === bookModel.coverColorLightMuted &&
    cached.metadata?.narrator === bookModel.narrator &&
    cached.metadata?.genre === bookModel.genre &&
    cached.metadata?.year === bookModel.year?.toString() &&
    cached.metadata?.description === bookModel.description &&
    cached.metadata?.copyright === bookModel.copyright
  );
}

function buildAuthors(bookMap: BookMap): Author[] {
  const authorsMap = new Map<string, Book[]>();
  for (const book of Object.values(bookMap)) {
    if (!authorsMap.has(book.author)) {
      authorsMap.set(book.author, []);
    }
    authorsMap.get(book.author)!.push(book);
  }
  return Array.from(authorsMap.entries())
    .map(([name, books]) => ({ name, books }))
    .sort((a, b) => a.name.localeCompare(b.name));
}

// Let TypeScript infer the store type from the create call.
export const useLibraryStore: UseBoundStore<StoreApi<LibraryState>> =
  create<LibraryState>()((set, get) => ({
    authors: [],
    books: {},
    playbackProgress: {},
    playbackIndex: {},
    setAuthors: (authors: Author[]) => set({ authors }),
    setPlaybackProgress: (bookId: string, progress: number) =>
      set((state) => ({
        playbackProgress: {
          ...state.playbackProgress,
          [bookId]: progress,
        },
      })),
    setPlaybackIndex: (bookId: string, index: number) =>
      set((state) => ({
        playbackIndex: {
          ...state.playbackIndex,
          [bookId]: index,
        },
      })),
    updateBookChapterIndex: async (
      bookId: string,
      chapterIndex: number,
    ) => {
      await database.write(async () => {
        const book = await database.collections
          .get<BookModel>('books')
          .find(bookId);
        await book.update((record) => {
          record.currentChapterIndex = chapterIndex;
        });
      });
    },
    getPlaybackProgress: (bookId: string) => get().playbackProgress[bookId],
    getPlaybackIndex: (bookId: string) => get().playbackIndex[bookId],
    refresh: async () => {
      const booksCollection = database.collections.get<BookModel>('books');
      const bookModels = await booksCollection.query().fetch();

      const newBookMap: BookMap = {};
      bookAuthorIdCache.clear();

      for (const bookModel of bookModels) {
        // Skip soft-deleted records
        if (bookModel._raw._status === 'deleted') continue;
        newBookMap[bookModel.id] = await convertBookModelToBook(bookModel);
      }

      const finalAuthorsData = buildAuthors(newBookMap);

      set({ authors: finalAuthorsData, books: newBookMap });
      scheduleAndroidAutoCacheWrite(finalAuthorsData); // debounced: keep AA browse tree in sync
    },
    init: () => {
      // Guard against duplicate subscriptions (memory leak prevention)
      const existingCleanup = get()._cleanup;
      if (existingCleanup) {
        if (__DEV__) {
          console.warn('Library store init called while already initialized');
        }
        return existingCleanup;
      }

      const booksCollection = database.collections.get<BookModel>('books');

      const subscriptions: Subscription[] = [];

      // Coalesce + serialize emissions: processing awaits DB fetches, so two
      // emissions can interleave and let a stale snapshot win the final set().
      // Each emission carries the FULL record set, so when one arrives while
      // another is processing, only the newest pending one needs to run.
      let pendingRecords: BookModel[] | null = null;
      let isProcessingEmission = false;

      const processEmission = async (changedRecords: BookModel[]) => {
        const { books: currentBooks } = get();

        // Create a mutable copy of the current books map
        const newBookMap = { ...currentBooks };

        // Detect books that were hard-deleted (no longer in query results)
        // The observer returns ALL books matching the query, so any book
        // in our store that's not in changedRecords has been deleted
        const currentDbBookIds = new Set(changedRecords.map((b) => b.id));
        for (const existingId of Object.keys(currentBooks)) {
          if (!currentDbBookIds.has(existingId)) {
            delete newBookMap[existingId];
            bookAuthorIdCache.delete(existingId);
          }
        }

        // Process each record from the database
        for (const bookModel of changedRecords) {
          // If the book was soft-deleted, remove it from our map
          if (bookModel._raw._status === 'deleted') {
            delete newBookMap[bookModel.id];
            bookAuthorIdCache.delete(bookModel.id);
            continue;
          }

          // Re-convert only records whose observed columns actually changed;
          // conversion costs two relation fetches per book.
          const cached = newBookMap[bookModel.id];
          if (cached && isCachedBookCurrent(cached, bookModel)) continue;

          newBookMap[bookModel.id] = await convertBookModelToBook(bookModel);
        }

        const finalAuthorsData = buildAuthors(newBookMap);

        set({
          authors: finalAuthorsData,
          books: newBookMap,
        });
        scheduleAndroidAutoCacheWrite(finalAuthorsData); // debounced: keep AA browse tree in sync
      };

      const booksSubscription = booksCollection
        .query()
        // Adding/removing a column here requires the matching comparison in
        // isCachedBookCurrent, or changes to it will be silently skipped.
        .observeWithColumns([
          'book_progress_value',
          'last_played_at',
          'finished_at',
          'title',
          'narrator',
          'genre',
          'year',
          'description',
          'copyright',
          'author_id',
          'artwork',
          'artwork_height',
          'artwork_width',
          'cover_color_dominant',
          'cover_color_vibrant',
          'cover_color_dark_vibrant',
          'cover_color_light_vibrant',
          'cover_color_muted',
          'cover_color_dark_muted',
          'cover_color_light_muted',
          'selected_accent_color_type',
        ])
        .subscribe((changedRecords) => {
          pendingRecords = changedRecords;
          if (isProcessingEmission) return;
          isProcessingEmission = true;
          void (async () => {
            try {
              while (pendingRecords !== null) {
                const batch = pendingRecords;
                pendingRecords = null;
                try {
                  await processEmission(batch);
                } catch (err) {
                  console.error(
                    'Library store: emission processing failed',
                    err,
                  );
                }
              }
            } finally {
              isProcessingEmission = false;
            }
          })();
        });

      subscriptions.push(booksSubscription);

      const cleanup = () => {
        subscriptions.forEach((sub) => sub.unsubscribe());
        set({ _cleanup: undefined });
      };

      set({ _cleanup: cleanup });
      return cleanup;
    },
    // The rest of your store logic is now inside the combine middleware
  }));

// This selector is still fine for author-level views.
export const useAuthors = () => useLibraryStore((state) => state.authors);

/**
 * Force refresh the library store from the database.
 * Call this after destructive operations that may not trigger the observer.
 */
export const refreshLibraryStore = () =>
  useLibraryStore.getState().refresh();

// This selector is inefficient and should be deprecated or updated to use the book map.
// For now, I'll leave it, but you should transition away from using it.
export const useBook = (author: string, bookTitle: string) =>
  useLibraryStore((state) => {
    const authorFound = state.authors.find((a) => a.name === author);
    return authorFound?.books.find((b) => b.bookTitle === bookTitle);
  });

/**
 * This is the new, highly performant way to get a book by its ID.
 * It directly accesses the book from the map in the store.
 */
export const useBookById = (bookId: string) => {
  return useLibraryStore((state) => state.books[bookId]);
};

/**
 * A new, more specific selector for getting just the data needed for a grid item.
 * This prevents re-renders if other book data (like chapter details) changes.
 * The `shallow` comparison is important for objects.
 */
export const useBookDisplayData = (bookId: string) =>
  useLibraryStore(
    useShallow((state) =>
      state.books[bookId]
        ? {
            bookId: state.books[bookId].bookId,
            author: state.books[bookId].author,
            bookTitle: state.books[bookId].bookTitle,
            artwork: state.books[bookId].artwork,
            artworkHeight: state.books[bookId].artworkHeight,
            artworkWidth: state.books[bookId].artworkWidth,
            currentChapterProgress:
              state.books[bookId].bookProgress.currentChapterProgress,
          }
        : undefined,
    ),
  );
