import React from 'react';
import { render, screen } from '@testing-library/react-native';
import type { Book, Chapter } from '@/types/Book';
import { BookProgressState } from '@/helpers/bookProgressState';
import { BookDurationRow } from '../BookDurationRow';

/*
 * The library row's half of exact-or-null (spec decision 3, ticket 09).
 *
 * A Book whose chapter duration failed to extract (`scanLibrary`'s
 * `makeErrorChapter` stores `0`) must still render something a listener can
 * read. This row calls `approximateLocationInBook` BY NAME, so an unusable
 * duration counts as zero and reads the capsule a little low — cosmetic, and
 * the trade-off the spec names for this surface. A Book that cannot be
 * located at all falls back to the whole duration.
 *
 * ⚠ `@/store/library` and `@/hooks/useTheme` are mocked because both reach
 * WatermelonDB's SQLite adapter, which has no JS implementation here. Neither
 * is what this test is about. `BookDurationRow` itself imports no Player
 * adapter and no database — that is the property ticket 09 requires of it,
 * and a mock list this short is the evidence.
 */

jest.mock('@/hooks/useTheme', () => ({
  useTheme: () => ({
    colors: { textMuted: '#888', primary: '#f00' },
    activeColorScheme: 'dark',
  }),
}));

const storeState = { playbackProgress: {}, playbackIndex: {} };
jest.mock('@/store/library', () => ({
  useLibraryStore: { getState: () => storeState },
}));


/** One file per chapter → a multi-item Queue, where Book Position is summed. */
const chapter = (chapterDuration: number, index: number): Chapter =>
  ({
    chapterTitle: `Ch ${index + 1}`,
    chapterNumber: index + 1,
    chapterDuration,
    startMs: 0,
    url: `/${index + 1}.mp3`,
    author: 'A',
    bookTitle: 'B',
    isAutoGenerated: false,
  }) as Chapter;

const makeBook = (
  chapters: Chapter[],
  currentChapterIndex: number,
  currentChapterProgress: number,
): Book =>
  ({
    bookId: 'b1',
    chapters,
    bookDuration: 1800,
    bookProgress: { currentChapterIndex, currentChapterProgress },
    bookProgressValue: BookProgressState.Started,
  }) as unknown as Book;

/**
 * "Never `NaN`" as an assertion: `queryByText` walks every rendered Text, so
 * a fabricated number leaking into any of them fails this.
 */
const expectNoNaN = () => expect(screen.queryByText(/NaN/)).toBeNull();

describe('BookDurationRow with an unusable chapter duration', () => {
  it('renders a readable remaining time rather than NaN or nothing', async () => {
    const chapters = [chapter(0, 0), chapter(600, 1), chapter(600, 2)];
    await render(<BookDurationRow book={makeBook(chapters, 2, 30)} />);

    // 0 + 600 + 30 played of 1800 → 1170 remaining → "19m left"
    expect(screen.getByText('19m left')).toBeTruthy();
    expectNoNaN();
  });

  it('renders the whole duration when the Book cannot be located at all', async () => {
    const chapters = [chapter(600, 0), chapter(600, 1), chapter(600, 2)];
    // A stored index pointing at no row: this used to be CLAMPED to the last
    // chapter, reading as a Book that is nearly finished.
    await render(<BookDurationRow book={makeBook(chapters, 9, 30)} />);

    expect(screen.getByText('30m left')).toBeTruthy();
    expectNoNaN();
  });

  it('renders a Book it can measure exactly the same way', async () => {
    const chapters = [chapter(600, 0), chapter(600, 1), chapter(600, 2)];
    await render(<BookDurationRow book={makeBook(chapters, 1, 60)} />);

    // 600 + 60 played of 1800 → 1140 remaining
    expect(screen.getByText('19m left')).toBeTruthy();
  });
});
