import database from '@/db';
import Footprint, { FootprintTrigger } from '@/db/models/Footprint';
import Book from '@/db/models/Book';
import Chapter from '@/db/models/Chapter';
import { Q } from '@nozbe/watermelondb';
import { getActiveTrackIndex, getProgress } from '@/player/trackPlayer';
import { usesChapterQueue } from '@/helpers/chapterPlayback';

const MAX_FOOTPRINTS_PER_BOOK = 10;

type ChapterData = {
  startMs: number;
  url: string;
  // Required by usesChapterQueue's memory gate and auto-chapter exclusion
  // (see ChapterLike in chapterPlayback.ts) — omitting either would make
  // this file's queue-shape verdict diverge from the queue builders' for
  // oversized or auto-chaptered books.
  chapterDuration: number;
  isAutoGenerated: boolean;
};

/**
 * Calculate the current chapter index for a book based on playback position.
 * For single-file books, this calculates the chapter from position.
 * For multi-file books, this returns the track index.
 *
 * ⚠ KNOWN LAYERING VIOLATION, left standing deliberately.
 *
 * This is a persistence module, and it asks the Player where it is. Worse, it
 * then decides what Position is measured against for this Book -- which is a
 * question five different mechanisms in this app answer, by consulting
 * different sources, with results that can disagree. Persistence should be told
 * the answer, not work it out.
 *
 * The RNTP-adapter work does NOT fix this, by design. That pass makes this file
 * reach the Player through one adapter instead of by name, which changes the
 * shape of the coupling and not its direction. Fixing it properly means the
 * queue-shape question getting a module of its own, and this file asking that
 * module instead of deciding.
 *
 * The rule, so it survives without a pointer: NOTHING under db/ may decide what
 * Position is measured against. If you are here to add a second such decision,
 * that is the signal the module is overdue.
 */
export async function getCurrentChapterInfo(
  bookId: string,
): Promise<{ chapterIndex: number; positionInChapterMs: number } | null> {
  try {
    const [trackIndex, { position }] = await Promise.all([
      getActiveTrackIndex(),
      getProgress(),
    ]);

    if (trackIndex == null) return null;

    // Get book and chapters from database
    const bookRecord = await database.get<Book>('books').find(bookId);
    const chapters = await (bookRecord.chapters as any).fetch();

    if (chapters.length === 0) return null;

    // Sort chapters by their order (using startMs or track number)
    const sortedChapters: ChapterData[] = chapters
      .map((c: Chapter) => ({
        startMs: (c as any).startMs ?? 0,
        url: c.url,
        chapterDuration: c.chapterDuration ?? 0,
        isAutoGenerated: c.isAutoGenerated ?? false,
      }))
      .sort((a: ChapterData, b: ChapterData) => a.startMs - b.startMs);

    // Legacy single-file books are ONE queue item with absolute positions;
    // multi-file and clipped single-file books are chapter queues where the
    // track index IS the chapter index and positions are chapter-relative.
    if (!usesChapterQueue(sortedChapters)) {
      // Calculate chapter index from position
      const positionMs = position * 1000;
      let currentChapterIndex = 0;

      for (let i = sortedChapters.length - 1; i >= 0; i--) {
        if (positionMs >= sortedChapters[i].startMs) {
          currentChapterIndex = i;
          break;
        }
      }

      const chapterStartMs = sortedChapters[currentChapterIndex].startMs;
      const positionInChapterMs = Math.max(0, positionMs - chapterStartMs);

      return {
        chapterIndex: currentChapterIndex,
        positionInChapterMs: Math.round(positionInChapterMs),
      };
    } else {
      // Multi-file book - use track index directly
      // Position is already relative to the current track/chapter
      return {
        chapterIndex: trackIndex,
        positionInChapterMs: Math.round(position * 1000),
      };
    }
  } catch {
    return null;
  }
}

/**
 * Record a footprint with automatic chapter detection.
 * Handles both single-file and multi-file books correctly.
 */
export async function recordFootprint(
  bookId: string,
  triggerType: FootprintTrigger,
): Promise<void> {
  const chapterInfo = await getCurrentChapterInfo(bookId);
  if (!chapterInfo) return;

  await addFootprint(
    bookId,
    chapterInfo.chapterIndex,
    chapterInfo.positionInChapterMs,
    triggerType,
  );
}

/**
 * Record a seek footprint with the position BEFORE the seek.
 * For single-file books, calculates chapter from the given position.
 * @param bookId - The book ID
 * @param positionBeforeSeekMs - The playback position (in ms) BEFORE the seek started
 */
export async function recordSeekFootprint(
  bookId: string,
  positionBeforeSeekMs: number,
): Promise<void> {
  try {
    // Get book and chapters from database
    const bookRecord = await database.get<Book>('books').find(bookId);
    const chapters = await (bookRecord.chapters as any).fetch();

    if (chapters.length === 0) return;

    // Sort chapters by their order
    const sortedChapters: ChapterData[] = chapters
      .map((c: Chapter) => ({
        startMs: (c as any).startMs ?? 0,
        url: c.url,
        chapterDuration: c.chapterDuration ?? 0,
        isAutoGenerated: c.isAutoGenerated ?? false,
      }))
      .sort((a: ChapterData, b: ChapterData) => a.startMs - b.startMs);

    let chapterIndex: number;
    let positionInChapterMs: number;

    // Same mode split as getCurrentChapterInfo above: only legacy
    // single-file books derive the chapter from an absolute position.
    if (!usesChapterQueue(sortedChapters)) {
      // Calculate chapter index from the position before seek
      chapterIndex = 0;
      for (let i = sortedChapters.length - 1; i >= 0; i--) {
        if (positionBeforeSeekMs >= sortedChapters[i].startMs) {
          chapterIndex = i;
          break;
        }
      }
      const chapterStartMs = sortedChapters[chapterIndex].startMs;
      positionInChapterMs = Math.max(
        0,
        positionBeforeSeekMs - chapterStartMs,
      );
    } else {
      // Multi-file book - get current track index
      const trackIndex = await getActiveTrackIndex();
      chapterIndex = trackIndex ?? 0;
      positionInChapterMs = positionBeforeSeekMs;
    }

    await addFootprint(
      bookId,
      chapterIndex,
      Math.round(positionInChapterMs),
      'seek',
    );
  } catch {
    // Silently fail
  }
}

export const TRIGGER_LABELS: Record<FootprintTrigger, string> = {
  play: 'Play pressed',
  seek: 'Seeked from',
  chapter_change: 'Chapter changed',
  chapter_restart: 'Chapter restart',
  timer_activation: 'Timer started at',
};

export function formatRelativeTime(timestamp: number): string {
  const now = Date.now();
  const diff = now - timestamp;
  const minutes = Math.floor(diff / 60000);
  const hours = Math.floor(diff / 3600000);
  const days = Math.floor(diff / 86400000);

  if (minutes < 1) return 'Just now';
  if (minutes < 60) return `${minutes}m ago`;
  if (hours < 24) return `${hours}h ago`;
  return `${days}d ago`;
}

export async function addFootprint(
  bookId: string,
  chapterIndex: number,
  positionMs: number,
  triggerType: FootprintTrigger,
): Promise<void> {
  await database.write(async () => {
    const footprintsCollection =
      database.collections.get<Footprint>('footprints');

    // Get existing footprints for this book, ordered by created_at DESC
    const existingFootprints = await footprintsCollection
      .query(Q.where('book_id', bookId), Q.sortBy('created_at', Q.desc))
      .fetch();

    // If we have MAX_FOOTPRINTS_PER_BOOK or more, delete the oldest ones
    if (existingFootprints.length >= MAX_FOOTPRINTS_PER_BOOK) {
      const footprintsToDelete = existingFootprints.slice(
        MAX_FOOTPRINTS_PER_BOOK - 1,
      );
      for (const fp of footprintsToDelete) {
        await fp.destroyPermanently();
      }
    }

    // Create new footprint
    await footprintsCollection.create((fp) => {
      fp.bookId = bookId;
      fp.chapterIndex = chapterIndex;
      fp.positionMs = positionMs;
      fp.triggerType = triggerType;
      fp.createdAt = Date.now();
    });
  });
}

export async function getFootprints(bookId: string): Promise<Footprint[]> {
  const footprintsCollection =
    database.collections.get<Footprint>('footprints');

  return footprintsCollection
    .query(Q.where('book_id', bookId), Q.sortBy('created_at', Q.asc))
    .fetch();
}

export async function deleteFootprintsForBook(
  bookId: string,
): Promise<void> {
  await database.write(async () => {
    const footprintsCollection =
      database.collections.get<Footprint>('footprints');

    const footprints = await footprintsCollection
      .query(Q.where('book_id', bookId))
      .fetch();

    for (const fp of footprints) {
      await fp.destroyPermanently();
    }
  });
}
