import type { Track } from '@/player/trackPlayer';
import type { Book, Chapter } from '@/types/Book';
import { resolveTrackArtwork } from '@/helpers/defaultArtwork';
import { CLIPPED_CHAPTERS_SPIKE } from '@/constants/featureFlags';
import { getHeapLimitBytes } from '@/helpers/deviceHeap';
import { hasValidChapterData } from '@/helpers/chapterMetadata';

/**
 * The chapter fields the gate reads. Exported because `queueShapeOf` folds
 * this gate into its verdict and must accept exactly the same projection —
 * a second, drifting copy of this type is how a Book slips past the gate in
 * one module while the queue builders reject it.
 */
export type GateChapter = Pick<
  Chapter,
  'url' | 'startMs' | 'chapterDuration' | 'isAutoGenerated'
>;

/**
 * More than one Chapter, all pointing at the same file.
 *
 * ⚠ PRIVATE, and it must stay that way. This used to be an exported
 * `isSingleFileBook()` and was one of the nine Queue-shape mechanisms the
 * queue-shape work deleted — it answered about the BOOK ON DISK while every
 * caller was really asking about the Queue, which CONTEXT.md's **Queue shape**
 * entry lists "single-file" under _Avoid_ for. `queueShapeOf` is the only
 * answer to that question now, and it composes its own `length > 0` above
 * this gate rather than reusing this `> 1`.
 *
 * The `> 1` here is load-bearing, but only TOGETHER with the one in
 * `hasValidChapterData` below: flipping either alone changes no verdict, and
 * flipping both would make a one-Chapter Book clippable. Neither was touched.
 */
function multipleChaptersInOneFile(
  chapters: readonly Pick<Chapter, 'url'>[] | undefined,
): boolean {
  if (!chapters || chapters.length <= 1) return false;
  return chapters.every((c) => c.url === chapters[0].url);
}

/**
 * Estimated Java-heap bytes ExoPlayer needs at a clipped-chapter transition.
 *
 * Each clipped queue item is its own ProgressiveMediaSource, and Mp4Extractor
 * materializes the file's FULL sample table per prepared period: ~24 B per
 * AAC frame (long[] offsets + int[] sizes + long[] timestamps + int[] flags),
 * at 44100/1024 ≈ 43.07 frames per second. Two periods coexist while the
 * next chapter is prepared, hence the ×2. Device-verified: a 28.7 h book
 * measured ~107 MB per period and OOM'd at every boundary on a 256 MiB heap.
 *
 * The sample rate is assumed to be 44.1 kHz (the worst common case) because
 * the real rate isn't available from chapter rows and this function must be
 * a pure function of `chapters` — every call site (queue builders AND the
 * helpers that interpret queue shape) has to reach the same verdict. The
 * assumption overestimates 2× for 22.05 kHz books, which only errs toward
 * the safe legacy path.
 */
const SAMPLE_TABLE_BYTES_PER_SECOND = 24 * (44100 / 1024) * 2;

export function estimateClippedTransitionPeakBytes(
  chapters: readonly GateChapter[],
): number {
  const totalDurationSec = chapters.reduce(
    (sum, ch) => sum + (ch.chapterDuration || 0),
    0,
  );
  return totalDurationSec * SAMPLE_TABLE_BYTES_PER_SECOND;
}

// Fraction of the heap the transition peak may claim; the rest is app
// baseline (RN runtime, images, JS heap) plus safety margin.
const CLIPPED_HEAP_BUDGET_FRACTION = 0.5;

/**
 * True when a book should be loaded as clipped per-chapter queue items:
 * spike flag on, single file, real chapter start offsets present, chapters
 * not auto-generated, and the book's sample table small enough to survive
 * chapter transitions (oversized books fall back to the legacy single-track
 * path — see the estimator above).
 *
 * Auto-generated chapters are excluded because their boundaries are
 * synthetic (e.g. exact 30-min marks) with no corresponding seek point in
 * the file. These books are MP3s (no sample table), where ExoPlayer resolves
 * a clip start from a bitrate-estimated byte offset that can land ±seconds
 * off, audibly skipping/repeating audio at every boundary. The legacy path
 * never seeks at a boundary, so playback stays continuous.
 *
 * Accepts any chapter-shaped rows that carry `url` + `startMs` +
 * `chapterDuration` + `isAutoGenerated`. Rows missing `chapterDuration`
 * weaken the memory gate and rows missing `isAutoGenerated` dodge the
 * auto-chapter exclusion, so projections must include both.
 */
export function shouldUseClippedChapters(
  chapters: readonly GateChapter[] | undefined,
): boolean {
  if (
    !CLIPPED_CHAPTERS_SPIKE ||
    !multipleChaptersInOneFile(chapters) ||
    !hasValidChapterData(chapters) ||
    chapters!.some((ch) => ch.isAutoGenerated)
  ) {
    return false;
  }
  return (
    estimateClippedTransitionPeakBytes(chapters!) <=
    getHeapLimitBytes() * CLIPPED_HEAP_BUDGET_FRACTION
  );
}

/**
 * Builds one Track per chapter, all pointing at the same file, each playing
 * only its chapter's time window. `clipStartMs`/`clipEndMs` are consumed by
 * the patched native Track → MediaItem.ClippingConfiguration. The last
 * chapter leaves clipEndMs undefined (plays to end of source). Positions and
 * durations inside each queue item are chapter-relative, matching how
 * a Book with one file per Chapter already behaves — and matching the
 * chapter-relative progress the DB already stores for a Book in one file.
 */
export function buildClippedChapterTracks(book: Book): Track[] {
  const chapters = book.chapters ?? [];
  return chapters.map((ch, i) => ({
    url: chapters[0].url,
    title: ch.chapterTitle,
    artist: book.author,
    artwork: resolveTrackArtwork(book.artwork),
    album: book.bookTitle,
    bookId: book.bookId,
    duration: ch.chapterDuration,
    mediaId: `${book.bookId}_ch${i}`,
    clipStartMs: ch.startMs ?? 0,
    clipEndMs: chapters[i + 1]?.startMs,
  }));
}
