import type { Track } from '@/player/trackPlayer';
import type { Book, Chapter } from '@/types/Book';
import { resolveTrackArtwork } from '@/helpers/defaultArtwork';
import { CLIPPED_CHAPTERS_SPIKE } from '@/constants/featureFlags';
import { getHeapLimitBytes } from '@/helpers/deviceHeap';
import {
  isSingleFileBook,
  hasValidChapterData,
} from '@/helpers/singleFileBook';

/**
 * The chapter fields the gate reads. Exported because `queueShapeOf` folds
 * this gate into its verdict and must accept exactly the same projection —
 * a second, drifting copy of this type is how a Book slips past the gate in
 * one module while the queue builders reject it.
 */
export type GateChapter = Pick<
  Chapter,
  'url' | 'startMs' | 'chapterDuration' | 'isAutoGenerated'
>;

/**
 * Estimated Java-heap bytes ExoPlayer needs at a clipped-chapter transition.
 *
 * Each clipped queue item is its own ProgressiveMediaSource, and Mp4Extractor
 * materializes the file's FULL sample table per prepared period: ~24 B per
 * AAC frame (long[] offsets + int[] sizes + long[] timestamps + int[] flags),
 * at 44100/1024 ≈ 43.07 frames per second. Two periods coexist while the
 * next chapter is prepared, hence the ×2. Device-verified: a 28.7 h book
 * measured ~107 MB per period and OOM'd at every boundary on a 256 MiB heap.
 *
 * The sample rate is assumed to be 44.1 kHz (the worst common case) because
 * the real rate isn't available from chapter rows and this function must be
 * a pure function of `chapters` — every call site (queue builders AND the
 * helpers that interpret queue shape) has to reach the same verdict. The
 * assumption overestimates 2× for 22.05 kHz books, which only errs toward
 * the safe legacy path.
 */
const SAMPLE_TABLE_BYTES_PER_SECOND = 24 * (44100 / 1024) * 2;

export function estimateClippedTransitionPeakBytes(
  chapters: readonly GateChapter[],
): number {
  const totalDurationSec = chapters.reduce(
    (sum, ch) => sum + (ch.chapterDuration || 0),
    0,
  );
  return totalDurationSec * SAMPLE_TABLE_BYTES_PER_SECOND;
}

// Fraction of the heap the transition peak may claim; the rest is app
// baseline (RN runtime, images, JS heap) plus safety margin.
const CLIPPED_HEAP_BUDGET_FRACTION = 0.5;

/**
 * True when a book should be loaded as clipped per-chapter queue items:
 * spike flag on, single file, real chapter start offsets present, chapters
 * not auto-generated, and the book's sample table small enough to survive
 * chapter transitions (oversized books fall back to the legacy single-track
 * path — see the estimator above).
 *
 * Auto-generated chapters are excluded because their boundaries are
 * synthetic (e.g. exact 30-min marks) with no corresponding seek point in
 * the file. These books are MP3s (no sample table), where ExoPlayer resolves
 * a clip start from a bitrate-estimated byte offset that can land ±seconds
 * off, audibly skipping/repeating audio at every boundary. The legacy path
 * never seeks at a boundary, so playback stays continuous.
 *
 * Accepts any chapter-shaped rows that carry `url` + `startMs` +
 * `chapterDuration` + `isAutoGenerated`. Rows missing `chapterDuration`
 * weaken the memory gate and rows missing `isAutoGenerated` dodge the
 * auto-chapter exclusion, so projections must include both.
 */
export function shouldUseClippedChapters(
  chapters: readonly GateChapter[] | undefined,
): boolean {
  if (
    !CLIPPED_CHAPTERS_SPIKE ||
    !isSingleFileBook(chapters) ||
    !hasValidChapterData(chapters) ||
    chapters!.some((ch) => ch.isAutoGenerated)
  ) {
    return false;
  }
  return (
    estimateClippedTransitionPeakBytes(chapters!) <=
    getHeapLimitBytes() * CLIPPED_HEAP_BUDGET_FRACTION
  );
}

/**
 * Whether this Book loads as ONE queue item, so positions are absolute and
 * chapters are seek offsets inside a single track.
 *
 * The one place every press site asks that question. It is NOT
 * `book.isSingleFile` on its own and it is NOT `queue.length === 1`: a
 * single-file Book that clears the memory gate above is loaded as one clipped
 * queue item PER CHAPTER, so it is single-file in the DB and a chapter queue
 * at runtime. Splitting the verdict across sites is what let the in-app
 * skip-next button reach a different answer from the notification press for
 * the same Book.
 *
 * It lives here, beside the gate it folds in, rather than in the playback
 * service that used to own it: `setup/service.ts` is a leaf module — nothing
 * in `src/` imports it — so a component asking this question could not reach
 * the service's copy. There is no state to reach either; this is a pure
 * function of the Book, which is a requirement `shouldUseClippedChapters`
 * documents for itself.
 *
 * ⚠ This is a WAYPOINT, not a ruling. `.scratch/queue-shape/spec.md` owns the
 * question of how queue shape should really be resolved and is expected to
 * supersede this helper; deduplicating the existing answer here changes no
 * verdict, and when that spec lands it updates one helper instead of chasing
 * each call site separately.
 */
export function treatAsSingleFile(book: Book | undefined): boolean {
  return (
    (book?.isSingleFile ?? false) && !shouldUseClippedChapters(book?.chapters)
  );
}

/**
 * Builds one Track per chapter, all pointing at the same file, each playing
 * only its chapter's time window. `clipStartMs`/`clipEndMs` are consumed by
 * the patched native Track → MediaItem.ClippingConfiguration. The last
 * chapter leaves clipEndMs undefined (plays to end of source). Positions and
 * durations inside each queue item are chapter-relative, matching how
 * multi-file books already behave — and matching the chapter-relative
 * progress the DB already stores for single-file books.
 */
export function buildClippedChapterTracks(book: Book): Track[] {
  const chapters = book.chapters ?? [];
  return chapters.map((ch, i) => ({
    url: chapters[0].url,
    title: ch.chapterTitle,
    artist: book.author,
    artwork: resolveTrackArtwork(book.artwork),
    album: book.bookTitle,
    bookId: book.bookId,
    duration: ch.chapterDuration,
    mediaId: `${book.bookId}_ch${i}`,
    clipStartMs: ch.startMs ?? 0,
    clipEndMs: chapters[i + 1]?.startMs,
  }));
}
