import type { Chapter } from '@/types/Book';
import { shouldUseClippedChapters } from '@/helpers/clippedChapters';

/**
 * Whether a Book's Queue is ONE item spanning the whole Book, or one item per
 * Chapter. It is a property of the QUEUE, not of the Book: the same Book can
 * take different shapes on different devices, because the clipped-chapters
 * memory gate depends on the device heap.
 *
 * The vocabulary is `bookEndDetection.ts`'s, reused verbatim: that module
 * already ships it, device-verified on both shapes, with a documented
 * fail-closed rule — anything that is not exactly `'one-item'` is treated as
 * multi-item. This module follows the same rule for undecidable input.
 *
 * ─── Why this is pure and synchronous ───────────────────────────────────
 *
 * Nothing here imports `@/player/*`, does IO, or logs. That is a requirement,
 * not a coincidence — it is ADR 0003's decision 2 applied one layer up (the IO
 * half must not decide, and the deciding half must not do IO):
 *
 * - The two queue BUILDERS ask this in order to build a Queue, so there is no
 *   Queue to observe yet. An async, Player-reading verdict would leave the two
 *   sites that most need one answer keeping their own.
 * - `BookDurationRow` asks it once per visible library row and is deliberately
 *   unmemoized. A signature that forced a Player read would pull an async
 *   bridge call into a FlashList row.
 *
 * ─── Why the memo below is sound, and what would break it ───────────────
 *
 * The verdict is memoised on a `WeakMap` keyed by the chapters ARRAY
 * REFERENCE. There is no invalidation code because there is nothing to
 * invalidate: a rescan produces a new array and the old entry is collected.
 *
 * That works only because the verdict's other two inputs are
 * PROCESS-CONSTANT:
 *
 * - `CLIPPED_CHAPTERS_SPIKE` is a compile-time constant.
 * - `getHeapLimitBytes()` reads native once and caches (`deviceHeap.ts`).
 *
 * ⚠ If either ever becomes runtime-variable — a settings toggle for the
 * spike, a heap limit re-read after a configuration change — this memo will
 * SILENTLY SERVE STALE VERDICTS WITH NO SYMPTOM. There is no assertion that
 * can catch it, because a stale verdict is a perfectly well-formed answer.
 * Whoever makes either input variable must revisit this memo in the same
 * change.
 *
 * The array reference is stable in practice: the library store caches Book
 * objects and skips re-conversion via `isCachedBookCurrent`, and
 * `currentChapterProgress` is not in the observed column list, so per-tick
 * progress writes do not re-convert the Book.
 */
export type QueueShape = 'one-item' | 'multi-item';

/**
 * The fields the verdict reads. `chapterDuration` feeds the memory gate and
 * `isAutoGenerated` the auto-chapter exclusion inside
 * `shouldUseClippedChapters`, so a projection that omits either would let a
 * Book slip past the gate here while the queue builders — holding full
 * chapter rows — reject it. That split is the disease this module exists to
 * cure, so the type refuses to allow it.
 */
export type ShapeChapter = Pick<
  Chapter,
  'url' | 'startMs' | 'chapterDuration' | 'isAutoGenerated'
>;

const verdicts = new WeakMap<readonly ShapeChapter[], QueueShape>();

/**
 * ⚠ `chapters.length > 0`, NOT `> 1`.
 *
 * `isSingleFileBook()` (`> 1`) and the persisted `book.isSingleFile` flag
 * (`> 0`) are the same predicate written twice, with an off-by-one in the
 * copy everything downstream reads. Today a ONE-CHAPTER Book makes
 * `treatAsSingleFile()` and `usesChapterQueue()` BOTH return true — "positions
 * are absolute" and "positions are chapter-relative" asserted about the same
 * Book. It does not bite only because such a Book has `startMs: 0`, so the two
 * coordinate systems coincide.
 *
 * A one-chapter Book is one Queue item. This function says so.
 */
function deriveQueueShape(
  chapters: readonly ShapeChapter[] | undefined,
): QueueShape {
  if (!chapters || chapters.length === 0) return 'multi-item';

  const firstUrl = chapters[0].url;
  const oneFile = chapters.every((c) => c.url === firstUrl);
  if (!oneFile) return 'multi-item';

  // A single file whose chapters clear the memory gate is loaded as one
  // CLIPPED queue item per chapter — single-file in the DB, chapter queue at
  // runtime.
  return shouldUseClippedChapters(chapters) ? 'multi-item' : 'one-item';
}

/**
 * The Queue shape a Book's chapters produce. See the module header for why
 * this is pure, and for the two facts the memo depends on.
 *
 * Undecidable input (no chapters at all) answers `'multi-item'`, following
 * `bookEndDetection`'s fail-closed direction: a multi-item answer then
 * REQUIRES a usable chapter array downstream, so a missing one leaves a Book
 * unhandled rather than confidently mishandled.
 */
export function queueShapeOf(
  chapters: readonly ShapeChapter[] | undefined,
): QueueShape {
  if (!chapters) return 'multi-item';

  const cached = verdicts.get(chapters);
  if (cached !== undefined) return cached;

  const verdict = deriveQueueShape(chapters);
  verdicts.set(chapters, verdict);
  return verdict;
}
