import { Book, Chapter } from '@/types/Book';
import AuthorModel from '@/db/models/Author';
import BookModel from '@/db/models/Book';
import ChapterModel from '@/db/models/Chapter';
import * as RNFS from '@dr.pogodin/react-native-fs';
import * as MediaLibrary from 'expo-media-library';
import database from '@/db';
import { Q } from '@nozbe/watermelondb';
import ImageResizer from '@bam.tech/react-native-image-resizer';
import { populateSingleBook } from '@/hooks/usePopulateDatabase';
import {
  getLibraryFolderEntries,
  getAutoChapterInterval,
  setLastScanAt,
} from '@/db/settingsQueries';
import {
  analyzeFileWithMediaInfo,
  analyzeFileWithMediaInfoNoCover,
  extractMetadataFromResult,
  ExtractedMetadata,
} from './mediainfo';
import { getMediaInfoBatch } from '@/lib/mediainfoAdapter';
import { readCueText } from '@/lib/SafCueReader';
import {
  enumerateAudioViaMediaStore,
  compareFilePathsNatural,
  libraryRootAbsPath,
  type CueScanContext,
} from '@/helpers/enumerateAudioViaMediaStore';
import { BookImageColors, extractImageColors } from './imageColorExtractor';
import { useScanProgressStore } from '@/hooks/useScanProgressStore';
import { ArtworkColors } from './gradientColorSorter';
import {
  generateAutoChapters,
  shouldGenerateAutoChapters,
} from './autoChapterGenerator';
import { artworkFilename, coverExtractionKey } from './artworkIdentity';

const DEFAULT_BOOK_ARTWORK_COLORS: ArtworkColors = {
  // average: null, // DEPRECATED: Removed from color extraction
  dominantAndroid: null,
  vibrant: null,
  darkVibrant: null,
  lightVibrant: null,
  muted: null,
  darkMuted: null,
  lightMuted: null,
};

/**
 * One chapter record produced by the metadata-extraction phase of a scan,
 * consumed by groupChaptersIntoBooks. Every producer (buildBookMetadata,
 * makeErrorChapter) must emit this exact shape — the pipeline was previously
 * any[], which let a mismatched error-chapter shape produce books with an
 * undefined title.
 */
export type ScannedChapter = {
  author: string;
  narrator: string;
  bookTitle: string;
  chapterTitle: string;
  chapterNumber: number;
  year: number | null;
  description?: string;
  genre?: string;
  sampleRate?: number;
  codec?: string;
  bitrate?: number;
  copyright?: string;
  artworkUri: null;
  totalTrackCount: number;
  coverBase64: string | null;
  coverWidth: number | null;
  coverHeight: number | null;
  ctime: Date;
  /** Not set by any current producer; grouping persists it as null. */
  mtime?: Date;
  chapterDuration: number;
  startMs: number;
  url: string;
  /** True when chapters came from embedded (MediaInfo) chapter data. */
  fromEmbeddedChapters?: boolean;
};

/**
 * Groups chapter metadata into book structures.
 * Returns array of { authorName, book } for immediate processing.
 * If autoChapterInterval is provided, books with <= 1 chapter will have
 * auto-generated chapters created at the specified interval.
 */
function groupChaptersIntoBooks(
  chapters: ScannedChapter[],
): { authorName: string; book: Book }[] {
  const bookMap = new Map<string, { authorName: string; book: Book }>();

  for (const chapter of chapters) {
    const bookKey = `${chapter.author}::${chapter.bookTitle}`;

    if (!bookMap.has(bookKey)) {
      bookMap.set(bookKey, {
        authorName: chapter.author,
        book: {
          bookId: chapter.url,
          author: chapter.author,
          bookTitle: chapter.bookTitle,
          chapters: [],
          bookDuration: 0,
          artwork: chapter.coverBase64 || null,
          artworkHeight: chapter.coverHeight || null,
          artworkWidth: chapter.coverWidth || null,
          artworkColors: DEFAULT_BOOK_ARTWORK_COLORS,
          selectedAccentColorType: null,
          bookProgress: {
            currentChapterIndex: 0,
            currentChapterProgress: 0,
          },
          bookProgressValue: 0,
          lastPlayedAt: null,
          finishedAt: null,
          hasAutoGeneratedChapters: false,
          metadata: {
            year: chapter.year,
            description: chapter.description,
            narrator: chapter.narrator,
            genre: chapter.genre,
            sampleRate: chapter.sampleRate,
            bitrate: chapter.bitrate,
            copyright: chapter.copyright,
            codec: chapter.codec,
            totalTrackCount: chapter.totalTrackCount,
            ctime: chapter.ctime,
            mtime: chapter.mtime || null,
            // Scan-state only (not persisted): tells applyCueChaptersToBooks
            // to leave this book alone — its chapters came from MediaInfo.
            fromEmbeddedChapters: chapter.fromEmbeddedChapters === true,
          },
        },
      });
    }

    const entry = bookMap.get(bookKey)!;
    const chapterData: Chapter = {
      author: chapter.author,
      bookTitle: chapter.bookTitle,
      chapterTitle: chapter.chapterTitle,
      chapterNumber: chapter.chapterNumber,
      chapterDuration: chapter.chapterDuration,
      startMs: chapter.startMs,
      url: chapter.url,
      isAutoGenerated: false,
    };

    entry.book.chapters.push(chapterData);
    entry.book.bookDuration += chapterData.chapterDuration;
  }

  // Sort chapters within each book by chapter number and determine isSingleFile
  for (const entry of bookMap.values()) {
    if (entry.book.chapters.length > 1) {
      entry.book.chapters.sort((a, b) => a.chapterNumber - b.chapterNumber);
    }

    // Determine if this is a single-file book (all chapters have the same URL)
    const chapters = entry.book.chapters;
    entry.book.isSingleFile =
      chapters.length > 0 &&
      chapters.every((c) => c.url === chapters[0].url);
  }

  return Array.from(bookMap.values());
}

/**
 * Probes SAF for a .cue sidecar on each single-chapter book and replaces its
 * single chapter with cue-derived chapters when one is found and parses.
 *
 * Only runs for books with exactly one chapter (single-file audiobooks). A book
 * with `chapters.length > 1` is provably multi-file-or-m4b-with-embedded-chapters
 * — and per the format spec, multi-file books cannot have a .cue (cue INDEX
 * offsets are within a single file). So this gate skips with zero false
 * positives.
 *
 * `cueBasenames` is the set of `.cue` basenames found in the directory listing
 * (populated for free during readDir). Books whose audio file has no matching
 * cue basename short-circuit out, avoiding even an ENOENT SAF round-trip.
 */
async function applyCueChaptersToBooks(
  books: { authorName: string; book: Book }[],
  context: CueScanContext,
): Promise<void> {
  for (const { book } of books) {
    if (book.chapters.length !== 1) continue;
    // A book with even a single MediaInfo-embedded chapter is authoritative;
    // its sibling .cue (if any) must be ignored per the precedence rule.
    if (book.metadata?.fromEmbeddedChapters === true) continue;

    // NOTE: We deliberately do NOT pre-filter via the directory listing here.
    // Under scoped storage without MANAGE_EXTERNAL_STORAGE, File.listFiles()
    // (which RNFS.readDir wraps) is filtered to media MIMEs only — .cue files
    // are hidden from the listing entirely. We let the SAF probe itself be the
    // existence check; ENOENT for missing files is cheap (~50ms each) and the
    // gate above (chapters.length === 1 + !fromEmbeddedChapters) already
    // limits this to single-file books with no MediaInfo chapter data.

    const audioPath = book.chapters[0].url;
    const cueFilePath =
      audioPath.substring(0, audioPath.lastIndexOf('.')) + '.cue';
    const cueChapters = await parseCueFile(cueFilePath, context);
    if (!cueChapters || cueChapters.length === 0) continue;

    const firstChapter = book.chapters[0];
    const audioDurationMs = firstChapter.chapterDuration * 1000;

    const newChapters = cueChapters.map((cc, index) => {
      const next = cueChapters[index + 1];
      const endMs = next ? next.startMs : audioDurationMs;
      return {
        author: firstChapter.author,
        bookTitle: firstChapter.bookTitle,
        chapterTitle: cc.title || `Chapter ${index + 1}`,
        chapterNumber: index + 1,
        chapterDuration: Math.max(0, (endMs - cc.startMs) / 1000),
        startMs: cc.startMs,
        url: audioPath,
        isAutoGenerated: false,
      };
    });

    book.chapters = newChapters;
    book.bookDuration = newChapters.reduce(
      (sum, c) => sum + c.chapterDuration,
      0,
    );
    // Keep totalTrackCount in sync — populateSingleBook prefers
    // bookData.metadata.totalTrackCount over bookData.chapters.length, so the
    // stale `1` from the original single-chapter record would win otherwise.
    book.metadata.totalTrackCount = newChapters.length;
  }
}

/**
 * Replaces chapters with auto-generated time-sliced chapters on books that
 * lack real chapter data. Runs after the cue probe so cue-derived chapters
 * take precedence over auto-generated ones.
 */
function applyAutoChaptersToBooks(
  books: { authorName: string; book: Book }[],
  autoChapterInterval: number,
): void {
  for (const { book } of books) {
    if (
      !shouldGenerateAutoChapters(
        book.chapters.length,
        false,
        autoChapterInterval,
      )
    ) {
      continue;
    }
    const originalUrl = book.chapters[0]?.url || book.bookId;
    const generatedChapters = generateAutoChapters(
      book.bookDuration,
      autoChapterInterval,
    );
    book.chapters = generatedChapters.map((gc) => ({
      author: book.author,
      bookTitle: book.bookTitle,
      chapterTitle: gc.title,
      chapterNumber: gc.chapterNumber,
      chapterDuration: gc.chapterDuration,
      startMs: gc.startMs,
      url: originalUrl,
      isAutoGenerated: true,
    }));
    book.hasAutoGeneratedChapters = true;
  }
}

/**
 * Processes a single book: extracts artwork and writes to database.
 */
async function processAndPersistBook(
  authorName: string,
  book: Book,
): Promise<void> {
  try {
    const bookWithArtwork = await extractArtworkForBook(book);
    await populateSingleBook(authorName, bookWithArtwork);
  } catch (error) {
    console.error(
      `Error processing book "${book.bookTitle}" by ${authorName}:`,
      error,
    );
  } finally {
    // Always increment progress so UI reflects attempted processing
    useScanProgressStore.getState().incrementProcessedBooks();
  }
}

// Books persisted concurrently: overlaps one book's native image work
// (resize + palette extraction) with another's DB write. WatermelonDB
// serializes writes internally, so higher concurrency has diminishing
// returns while holding more decoded artwork in memory.
const PERSIST_CONCURRENCY = 2;

async function forEachWithPool<T>(
  items: T[],
  limit: number,
  fn: (item: T) => Promise<void>,
): Promise<void> {
  let nextIndex = 0;
  const workers = Array.from(
    { length: Math.min(limit, items.length) },
    async () => {
      while (nextIndex < items.length) {
        const item = items[nextIndex++];
        await fn(item);
      }
    },
  );
  await Promise.all(workers);
}

// Track which books already have cover art extracted (dir::author::title).
// Keyed per-directory to match book grouping: the same author+title in a
// different directory is a separate copy that needs its own extraction.
const booksWithCoverExtracted = new Set<string>();

/**
 * Checks if a chapter for this file needs cover extraction.
 * Returns true if any chapter belongs to a book we haven't seen yet.
 */
function needsCoverForFile(chapters: ScannedChapter[], dir: string): boolean {
  for (const chapter of chapters) {
    const bookTitle = chapter.bookTitle;
    if (!bookTitle) continue;

    const bookKey = coverExtractionKey(dir, chapter.author, bookTitle);
    if (!booksWithCoverExtracted.has(bookKey)) {
      booksWithCoverExtracted.add(bookKey);
      return true;
    }
  }
  return false;
}

/**
 * Processes the audio files discovered in a single directory: skips files
 * already represented in the DB (via the pre-built existingUrls Set), runs a
 * parallel MediaInfo batch on the remainder, groups results into books, probes
 * for sibling .cue files, generates auto-chapters when configured, and
 * persists each book.
 */
async function processDirectoryFiles(
  dir: string,
  audioFiles: string[],
  context: CueScanContext,
  autoChapterInterval: number | null,
  existingUrls: Set<string>,
): Promise<void> {
  try {
    const newFilesToProcess: string[] = [];
    for (const filePath of audioFiles) {
      if (!existingUrls.has(filePath)) {
        newFilesToProcess.push(filePath);
      }
    }
    // audioFiles is already sorted by enumerateAudioViaMediaStore; we sort
    // newFilesToProcess again only for the (rare) DB-filtered subset case.
    newFilesToProcess.sort(compareFilePathsNatural);

    const newChaptersInDir: ScannedChapter[] = [];

    if (newFilesToProcess.length > 0) {
      const batchResults = await getMediaInfoBatch(newFilesToProcess);

      for (let i = 0; i < newFilesToProcess.length; i++) {
        const filePath = newFilesToProcess[i];
        const result = batchResults[i];

        let metadata: ScannedChapter[];
        if (!result.json) {
          console.error(
            `MediaInfo batch returned no result for ${filePath}`,
          );
          metadata = [makeErrorChapter(filePath)];
        } else {
          const extracted = extractMetadataFromResult(result);
          metadata = buildChaptersFromMetadata(filePath, extracted);
        }

        if (needsCoverForFile(metadata, dir)) {
          metadata = await extractMetadata(filePath, false);
        }

        newChaptersInDir.push(...metadata);
      }
    }

    if (newChaptersInDir.length > 0) {
      const booksInDir = groupChaptersIntoBooks(newChaptersInDir);

      await applyCueChaptersToBooks(booksInDir, context);

      if (autoChapterInterval) {
        applyAutoChaptersToBooks(booksInDir, autoChapterInterval);
      }

      const progressStore = useScanProgressStore.getState();
      progressStore.setTotalBooks(
        progressStore.totalBooks + booksInDir.length,
      );

      await forEachWithPool(
        booksInDir,
        PERSIST_CONCURRENCY,
        ({ authorName, book }) => processAndPersistBook(authorName, book),
      );
    }
  } catch (err) {
    console.error(`Error processing directory ${dir}`, err);
  }
}

type CueChapter = { title: string; startMs: number };

const CUE_TITLE_REGEX = /^\s*TITLE\s*"(.*)"\s*$/;
const CUE_INDEX_REGEX = /^\s*INDEX\s*01\s*(\d+):(\d+):(\d+)\s*$/;
const CUE_FRAMES_PER_SECOND = 75;

/**
 * Parses a CUE sheet file and extracts chapter information.
 * Returns null if parsing fails or no chapters are found.
 *
 * Reads the file via SAF (using the tree URI granted at folder-add time)
 * because .cue files are not a media MIME and scoped storage blocks
 * path-based reads of non-media files under Android 11+.
 */
async function parseCueFile(
  cueFilePath: string,
  context: CueScanContext,
): Promise<CueChapter[] | null> {
  const prefix = context.rootAbsPath + '/';
  if (!cueFilePath.startsWith(prefix)) {
    console.warn(
      `cue path ${cueFilePath} not under tree root ${context.rootAbsPath}; cannot read via SAF`,
    );
    return null;
  }
  const relativePath = cueFilePath.substring(prefix.length);

  try {
    const cueContent = await readCueText(context.treeUri, relativePath);
    const lines = cueContent.split('\n');

    const chapters: CueChapter[] = [];
    let currentChapter: CueChapter | null = null;

    for (const line of lines) {
      const trimmedLine = line.trim();

      if (trimmedLine.startsWith('TRACK')) {
        if (currentChapter) {
          chapters.push(currentChapter);
        }
        currentChapter = { title: '', startMs: 0 };
        continue;
      }

      if (!currentChapter) continue;

      const titleMatch = trimmedLine.match(CUE_TITLE_REGEX);
      if (titleMatch) {
        currentChapter.title = titleMatch[1];
        continue;
      }

      const indexMatch = trimmedLine.match(CUE_INDEX_REGEX);
      if (indexMatch) {
        const minutes = parseInt(indexMatch[1], 10);
        const seconds = parseInt(indexMatch[2], 10);
        const frames = parseInt(indexMatch[3], 10);
        currentChapter.startMs =
          minutes * 60 * 1000 +
          seconds * 1000 +
          Math.round((frames / CUE_FRAMES_PER_SECOND) * 1000);
      }
    }

    if (currentChapter) {
      chapters.push(currentChapter);
    }

    return chapters.length > 0 ? chapters : null;
  } catch (error) {
    // Missing .cue is the common case (most books don't have a sidecar) — keep quiet.
    if ((error as { code?: string })?.code !== 'ENOENT') {
      console.error(`Failed to parse CUE file ${cueFilePath}:`, error);
    }
    return null;
  }
}

/**
 * Fallback author/book names derived from the file's parent directories,
 * used when tags are missing: .../<author>/<book title>/<file>.
 */
function pathBackupNames(filePath: string): {
  bookTitleBackup: string | undefined;
  authorBackup: string | undefined;
} {
  const dirPath = filePath.substring(0, filePath.lastIndexOf('/'));
  return {
    bookTitleBackup: dirPath.split('/').pop(),
    authorBackup: dirPath
      .substring(0, dirPath.lastIndexOf('/'))
      .split('/')
      .pop(),
  };
}

/**
 * Builds a book metadata object with common properties from file metadata.
 */
function buildBookMetadata(
  metadata: ExtractedMetadata,
  filePath: string,
  bookTitleBackup: string | undefined,
  authorBackup: string | undefined,
  chapterInfo: {
    title: string;
    number: number;
    duration: number;
    startMs: number;
    totalTracks: number;
  },
): ScannedChapter {
  // parseInt (not Number) so date-shaped tags like "2021-05-04" yield the
  // year instead of NaN; anything unparseable becomes null, never NaN.
  const parsedYear = Number.parseInt(metadata.releaseDate ?? '', 10);
  return {
    author: metadata.author || authorBackup || 'Unknown Author',
    narrator: metadata.narrator || 'Unknown Voice Artist',
    bookTitle: metadata.album || bookTitleBackup || 'Unknown Book',
    chapterTitle: chapterInfo.title,
    chapterNumber: chapterInfo.number,
    year: Number.isFinite(parsedYear) ? parsedYear : null,
    description: metadata.description,
    genre: metadata.genre,
    sampleRate: metadata.sampleRate,
    codec: metadata.codec,
    bitrate: metadata.bitrate,
    copyright: metadata.copyright,
    artworkUri: null,
    totalTrackCount: chapterInfo.totalTracks,
    coverBase64: metadata.cover || null,
    coverWidth: metadata.imgWidth || null,
    coverHeight: metadata.imgHeight || null,
    ctime: new Date(),
    chapterDuration: chapterInfo.duration,
    startMs: chapterInfo.startMs,
    url: filePath,
  };
}

/**
 * Builds chapter records from already-extracted ExtractedMetadata.
 * Factored out of extractMetadata so the streaming batch path can reuse it
 * without re-invoking the native side.
 *
 * Multi-chapter files are tagged `fromEmbeddedChapters: true` so the
 * post-grouping cue probe skips them — a single embedded chapter is still
 * authoritative over any sibling cue.
 */
function buildChaptersFromMetadata(
  filePath: string,
  metadata: ExtractedMetadata,
): ScannedChapter[] {
  const chapters = metadata.chapters || [];
  const { bookTitleBackup, authorBackup } = pathBackupNames(filePath);

  if (chapters.length > 0) {
    return chapters.map((chapter, index) => {
      const nextChapter = chapters[index + 1];
      const chapterEndMs = nextChapter
        ? nextChapter.startMs
        : metadata.durationMs || 0;
      const chapterDuration = (chapterEndMs - chapter.startMs) / 1000;

      return {
        ...buildBookMetadata(
          metadata,
          filePath,
          bookTitleBackup,
          authorBackup,
          {
            title: chapter.title || `Chapter ${index + 1}`,
            number: index + 1,
            duration: chapterDuration,
            startMs: chapter.startMs,
            totalTracks: chapters.length,
          },
        ),
        fromEmbeddedChapters: true,
      };
    });
  }

  // Single-chapter file (e.g. mp3)
  const chapterDuration = metadata.durationMs
    ? metadata.durationMs / 1000
    : 0;
  const fileName = filePath.split('/').pop() ?? '';
  //! could make chapterTitle an array and store the fileName.split as a backup chapter name that the user could switch to for specific titles (see Aracanum Unbounded)
  const chapterTitle =
    metadata.title || fileName.split('.')[0] || 'Unknown Chapter';

  return [
    buildBookMetadata(metadata, filePath, bookTitleBackup, authorBackup, {
      title: chapterTitle,
      number: metadata.trackPosition || 1,
      duration: chapterDuration,
      startMs: 0,
      totalTracks: 1,
    }),
  ];
}

/**
 * Placeholder chapter for a file whose metadata extraction failed, so the
 * file still appears in the library (named from its path) instead of
 * vanishing. Built through buildBookMetadata with empty tags to guarantee
 * the ScannedChapter shape stays in lockstep with the normal producers.
 */
function makeErrorChapter(filePath: string): ScannedChapter {
  const { bookTitleBackup, authorBackup } = pathBackupNames(filePath);
  const fileName = filePath.split('/').pop() ?? '';
  return buildBookMetadata({}, filePath, bookTitleBackup, authorBackup, {
    title: fileName.split('.')[0] || 'Unknown Chapter',
    number: 1,
    duration: 0,
    startMs: 0,
    totalTracks: 1,
  });
}

async function extractMetadata(
  filePath: string,
  skipCoverExtraction = false,
) {
  try {
    const metadata = skipCoverExtraction
      ? await analyzeFileWithMediaInfoNoCover(filePath)
      : await analyzeFileWithMediaInfo(filePath);
    return buildChaptersFromMetadata(filePath, metadata);
  } catch (error) {
    console.error(`Error extracting metadata for ${filePath}`, error);
    return [makeErrorChapter(filePath)];
  }
}

/**
 * Detects image format from base64 data.
 * Returns the appropriate file extension and whether the JPEG needs repair.
 */
function detectImageFormat(base64Data: string): {
  extension: 'png' | 'jpg';
  needsJpegRepair: boolean;
} {
  // Base64 signatures for common image formats
  const PNG_SIGNATURE = 'iVBOR';
  const TRUNCATED_JPEG_SIGNATURE = '/+'; // Missing FFD8 SOI header (normal JPEG starts with /9j/)

  const isPng = base64Data.startsWith(PNG_SIGNATURE);
  const needsJpegRepair = base64Data.startsWith(TRUNCATED_JPEG_SIGNATURE);

  return {
    extension: isPng ? 'png' : 'jpg',
    needsJpegRepair,
  };
}

/**
 * Writes image data to a temp file, repairing truncated JPEGs if needed.
 * Some MediaInfo extractions return JPEGs missing the SOI (FFD8) header.
 */
async function writeTempImageFile(
  tempFilePath: string,
  base64Data: string,
  needsJpegRepair: boolean,
): Promise<void> {
  if (needsJpegRepair) {
    // Prepend SOI marker (FFD8) before the data (which starts at FFE0/APP0)
    const soiMarker = new Uint8Array([0xff, 0xd8]);
    const soiString = String.fromCharCode(...soiMarker);
    await RNFS.writeFile(tempFilePath, soiString, 'ascii');
    await RNFS.appendFile(tempFilePath, base64Data, 'base64');
  } else {
    await RNFS.writeFile(tempFilePath, base64Data, 'base64');
  }
}

type ArtworkResult = {
  artworkUri: string | null;
  width: number;
  height: number;
};

let tempFileSeq = 0;

/**
 * Saves base64 artwork to a WebP file after resizing.
 * Handles truncated JPEG detection and repair.
 */
async function saveArtworkToFile(
  base64Artwork: string,
  bookTitle: string,
  author: string,
  bookUniqueKey: string,
): Promise<ArtworkResult> {
  const filename = artworkFilename(author, bookTitle, bookUniqueKey);

  const artworkDir = `${RNFS.DocumentDirectoryPath}/artwork`;
  const finalImagePath = `${artworkDir}/${filename}`;

  try {
    await RNFS.mkdir(artworkDir);

    const { extension, needsJpegRepair } = detectImageFormat(base64Artwork);
    // Sequence suffix: books persist concurrently, so Date.now() alone can
    // collide and two books would clobber each other's temp image.
    const tempFilePath = `${RNFS.CachesDirectoryPath}/temp_artwork_${Date.now()}_${++tempFileSeq}.${extension}`;

    await writeTempImageFile(tempFilePath, base64Artwork, needsJpegRepair);

    const resizedImage = await ImageResizer.createResizedImage(
      `file://${tempFilePath}`,
      800,
      800,
      'WEBP',
      80, //? COULD MAKE THIS A USER OPTION??
      0,
      undefined,
      false,
      { mode: 'contain', onlyScaleDown: true },
    );

    await RNFS.unlink(tempFilePath).catch(() => {});
    await RNFS.moveFile(resizedImage.path, finalImagePath);

    return {
      artworkUri: `file://${finalImagePath}`,
      width: resizedImage.width,
      height: resizedImage.height,
    };
  } catch (error) {
    console.error(`Failed to save artwork for ${bookTitle}:`, error);
    return { artworkUri: null, width: 0, height: 0 };
  }
}

const DEFAULT_ARTWORK_COLORS: BookImageColors = {
  // average: null, // DEPRECATED: Removed from extraction
  dominantAndroid: null,
  vibrant: null,
  darkVibrant: null,
  lightVibrant: null,
  muted: null,
  darkMuted: null,
  lightMuted: null,
};

// Default dimensions for placeholder artwork
const PLACEHOLDER_ARTWORK_SIZE = 500;

/**
 * Cleans and normalizes base64 image data from MediaInfo.
 * Handles multiple concatenated images and ensures valid base64 format.
 */
function cleanBase64ImageData(rawBase64: string): string {
  // MediaInfo may return multiple images separated by " / " - take only the first
  const firstImage = rawBase64.split(' / ')[0];

  // Remove all non-base64 characters
  let cleaned = firstImage.replace(/[^A-Za-z0-9+/=]/g, '');

  // Truncate at padding characters in the middle (indicates concatenated images)
  const paddingInMiddle = cleaned.search(/=+[^=]/);
  if (paddingInMiddle !== -1) {
    const paddingLength = cleaned.match(/=+/)?.[0]?.length ?? 0;
    cleaned = cleaned.substring(0, paddingInMiddle + paddingLength);
  }

  // Ensure length is a multiple of 4 (required for valid base64)
  const remainder = cleaned.length % 4;
  if (remainder !== 0) {
    cleaned = cleaned.substring(0, cleaned.length - remainder);
  }

  return cleaned;
}

/**
 * Extracts and processes artwork for a single book.
 * Returns the book with processed artwork data.
 */
async function extractArtworkForBook(book: Book): Promise<Book> {
  const rawBase64Artwork = book.artwork;

  if (!rawBase64Artwork) {
    return {
      ...book,
      artwork: null,
      artworkWidth: PLACEHOLDER_ARTWORK_SIZE,
      artworkHeight: PLACEHOLDER_ARTWORK_SIZE,
      artworkColors: DEFAULT_ARTWORK_COLORS,
    };
  }

  try {
    const cleanedBase64 = cleanBase64ImageData(rawBase64Artwork);

    const { artworkUri, width, height } = await saveArtworkToFile(
      cleanedBase64,
      book.bookTitle,
      book.author,
      // First chapter's file path: unique per copy even when two books share
      // author+title (e.g. same title, different narrators).
      book.bookId,
    );

    // Extract colors from saved file to reduce memory pressure
    const artworkColors = artworkUri
      ? await extractImageColors(artworkUri)
      : DEFAULT_ARTWORK_COLORS;

    return {
      ...book,
      artwork: artworkUri,
      artworkWidth: width,
      artworkHeight: height,
      artworkColors,
    };
  } catch (error) {
    console.error(`Error processing artwork for ${book.bookTitle}`, error);
    return {
      ...book,
      artwork: null,
      artworkWidth: null,
      artworkHeight: null,
      artworkColors: DEFAULT_ARTWORK_COLORS,
    };
  }
}

/**
 * Removes chapters from the database that no longer exist on disk,
 * then cleans up any orphaned books and authors.
 *
 * "Not enumerated by MediaStore" is not proof of deletion: MediaStore can
 * under-report (indexing lag, unavailable volume), and destroying a chapter
 * row also destroys the book's listening progress, which a future rescan
 * cannot restore. So a chapter under a configured root is only removed when
 * (a) its whole library root is still present on disk, and (b) a direct
 * existence probe confirms the file itself is gone. Chapters under no
 * configured root (user removed the folder from settings) are removed as
 * before. Probes only run for un-enumerated chapters — zero on a clean scan.
 */
async function removeMissingFiles(
  allFiles: string[],
  rootAbsPaths: string[],
): Promise<void> {
  const fileSet = new Set(allFiles);

  const allChapters = await database
    .get<ChapterModel>('chapters')
    .query()
    .fetch();

  const availableRoots = new Set<string>();
  for (const root of rootAbsPaths) {
    if (await RNFS.exists(root).catch(() => false)) {
      availableRoots.add(root);
    }
  }

  const chaptersToRemove: ChapterModel[] = [];
  for (const chapter of allChapters) {
    if (fileSet.has(chapter.url)) continue;

    const root = rootAbsPaths.find(
      (r) => chapter.url === r || chapter.url.startsWith(r + '/'),
    );
    if (root !== undefined) {
      if (!availableRoots.has(root)) continue;
      const stillOnDisk = await RNFS.exists(chapter.url).catch(() => false);
      if (stillOnDisk) continue;
    }

    chaptersToRemove.push(chapter);
  }

  // Orphaned books/authors are derived in memory from the surviving chapter
  // set (one pass over already-fetched rows) instead of a per-record
  // fetchCount query for every book and author.
  const removedChapterIds = new Set(chaptersToRemove.map((c) => c.id));
  const liveBookIds = new Set<string>();
  for (const chapter of allChapters) {
    if (!removedChapterIds.has(chapter.id)) {
      // Relation .id reads the foreign key without fetching the record
      liveBookIds.add((chapter.book as any).id);
    }
  }

  const allBooks = await database.get<BookModel>('books').query().fetch();
  const orphanedBooks = allBooks.filter((b) => !liveBookIds.has(b.id));

  const orphanedBookIds = new Set(orphanedBooks.map((b) => b.id));
  const liveAuthorIds = new Set<string>();
  for (const book of allBooks) {
    if (!orphanedBookIds.has(book.id)) {
      liveAuthorIds.add((book.author as any).id);
    }
  }

  const allAuthors = await database
    .get<AuthorModel>('authors')
    .query()
    .fetch();
  const orphanedAuthors = allAuthors.filter(
    (a) => !liveAuthorIds.has(a.id),
  );

  const removeCount =
    chaptersToRemove.length + orphanedBooks.length + orphanedAuthors.length;
  if (removeCount > 0) {
    // Single atomic batch: chapters, books, and authors go together, so a
    // crash mid-cleanup can't leave half-orphaned rows behind.
    await database.write(async () => {
      await database.batch(
        ...chaptersToRemove.map((c) => c.prepareDestroyPermanently()),
        ...orphanedBooks.map((b) => b.prepareDestroyPermanently()),
        ...orphanedAuthors.map((a) => a.prepareDestroyPermanently()),
      );
    });
  }
}

export async function scanLibrary(): Promise<void> {
  booksWithCoverExtracted.clear();

  const libraryEntries = await getLibraryFolderEntries();

  if (libraryEntries.length === 0) {
    console.log('No library folders configured. Aborting scan.');
    return;
  }

  // Permission gate. Defensive — the app already requests READ_MEDIA_AUDIO at
  // startup (useSetupTrackPlayer.tsx), but bail cleanly if the user declined.
  const perm = await MediaLibrary.getPermissionsAsync();
  if (perm.status !== 'granted') {
    console.log(
      `READ_MEDIA_AUDIO not granted (status=${perm.status}). Aborting scan.`,
    );
    return;
  }

  const autoChapterInterval = await getAutoChapterInterval();

  useScanProgressStore.getState().startScan();

  const { filesByDir, contexts, allFiles, nonFileUriSkipped } =
    await enumerateAudioViaMediaStore(libraryEntries);

  if (nonFileUriSkipped > 0) {
    console.warn(
      `MediaStore returned ${nonFileUriSkipped} non-file:// URIs which were skipped.`,
    );
  }

  // Bulk existence lookup: one chunked Q.oneOf query per ~500 paths instead of
  // a per-file fetchCount on the unindexed chapters.url column. Chunk size 500
  // stays well under SQLite's default SQLITE_MAX_VARIABLE_NUMBER (999).
  const existingUrls = new Set<string>();
  const EXIST_CHUNK_SIZE = 500;
  const chaptersCollection = database.get<ChapterModel>('chapters');
  for (let i = 0; i < allFiles.length; i += EXIST_CHUNK_SIZE) {
    const chunk = allFiles.slice(i, i + EXIST_CHUNK_SIZE);
    const rows = await chaptersCollection
      .query(Q.where('url', Q.oneOf(chunk)))
      .fetch();
    for (const row of rows) {
      existingUrls.add(row.url);
    }
  }

  const sortedDirs = Array.from(filesByDir.keys()).sort();
  for (const dir of sortedDirs) {
    const files = filesByDir.get(dir)!;
    const context = contexts.get(dir)!;
    await processDirectoryFiles(
      dir,
      files,
      context,
      autoChapterInterval,
      existingUrls,
    );
  }

  // Guard against the catastrophic "MediaStore returned nothing" case — if
  // allFiles is empty but the user has configured libraries, skip cleanup
  // rather than risk wiping every chapter from the DB.
  if (allFiles.length === 0) {
    console.warn(
      'MediaStore enumeration returned 0 files for configured libraries; ' +
        'skipping removeMissingFiles to avoid deleting all DB chapters.',
    );
  } else {
    await removeMissingFiles(
      allFiles,
      libraryEntries.map(libraryRootAbsPath),
    );
  }

  await setLastScanAt(Date.now());

  useScanProgressStore.getState().endScan();
}
