/**
 * The scan's file → book fold: many `ScannedChapter` records in, one `Book`
 * per (author, title) out.
 *
 * Split out of `scanLibrary.ts` so it can be tested. That file reaches RNFS,
 * MediaStore and the WatermelonDB instance, which makes every line in it
 * unreachable from jest (this repo runs jest on bare babel, with no RN
 * preset) — the same wall `generalTags.ts` was carved out of.
 *
 * It matters here specifically because this module owns the FIRST-FILE-WINS
 * rule and `generalTags.ts` now defers work on the strength of it. The rule
 * was stated at this consumer while the cost was paid at that producer, with
 * no test able to reach both; both are reachable now.
 *
 * ⚠ It also owns the chapter sort below, which is load-bearing well outside
 * this file: `chapters[0].url` after that sort is what `bookStructuralKey`
 * turns into `series_books.book_key`. See
 * `docs/adr/0001-series-membership-is-keyed-by-file-path.md`, and ticket 22,
 * which cites the sort as the reason the scan's key and the library store's
 * key agree in practice. Older notes cite it as `scanLibrary.ts:192`; it
 * lives here now.
 *
 * Deliberately free of runtime imports. Keep it that way.
 */
import type { Book, Chapter } from '@/types/Book';
import type { ArtworkColors } from './gradientColorSorter';
import type { DeferredTagBlob } from './generalTags';

const DEFAULT_BOOK_ARTWORK_COLORS: ArtworkColors = {
  // average: null, // DEPRECATED: Removed from color extraction
  dominantAndroid: null,
  vibrant: null,
  darkVibrant: null,
  lightVibrant: null,
  muted: null,
  darkMuted: null,
  lightMuted: null,
};

/**
 * One chapter record produced by the metadata-extraction phase of a scan,
 * consumed by groupChaptersIntoBooks. Every producer (buildBookMetadata,
 * makeErrorChapter) must emit this exact shape — the pipeline was previously
 * any[], which let a mismatched error-chapter shape produce books with an
 * undefined title.
 */
export type ScannedChapter = {
  author: string;
  narrator: string;
  bookTitle: string;
  chapterTitle: string;
  chapterNumber: number;
  year: number | null;
  description?: string;
  genre?: string;
  sampleRate?: number;
  codec?: string;
  bitrate?: number;
  copyright?: string;
  /**
   * Tags read off the file itself. Book-level values carried on a per-file
   * record, exactly like bitrate/sampleRate/codec above: grouping keeps the
   * first file's and never revisits it. Verified against the real corpus —
   * SERIES/PART/Grouping are identical across a book's files in 6/6 genuine
   * chapter-split directories.
   */
  series?: string;
  part?: number;
  grouping?: string;
  fileFormat?: string;
  /**
   * The fold below is the ONE site allowed to call this. See `DeferredTagBlob`
   * in generalTags.ts for why it is a thunk and what breaks at either extreme.
   */
  rawTagsJson?: DeferredTagBlob;
  artworkUri: null;
  totalTrackCount: number;
  coverBase64: string | null;
  coverWidth: number | null;
  coverHeight: number | null;
  ctime: Date;
  /** Not set by any current producer; grouping persists it as null. */
  mtime?: Date;
  chapterDuration: number;
  startMs: number;
  url: string;
  /** True when chapters came from embedded (MediaInfo) chapter data. */
  fromEmbeddedChapters?: boolean;
};

/**
 * Groups chapter metadata into book structures.
 * Returns array of { authorName, book } for immediate processing.
 * If autoChapterInterval is provided, books with <= 1 chapter will have
 * auto-generated chapters created at the specified interval.
 */
export function groupChaptersIntoBooks(
  chapters: ScannedChapter[],
): { authorName: string; book: Book }[] {
  const bookMap = new Map<string, { authorName: string; book: Book }>();

  for (const chapter of chapters) {
    const bookKey = `${chapter.author}::${chapter.bookTitle}`;

    if (!bookMap.has(bookKey)) {
      bookMap.set(bookKey, {
        authorName: chapter.author,
        book: {
          bookId: chapter.url,
          author: chapter.author,
          bookTitle: chapter.bookTitle,
          chapters: [],
          bookDuration: 0,
          artwork: chapter.coverBase64 || null,
          artworkHeight: chapter.coverHeight || null,
          artworkWidth: chapter.coverWidth || null,
          artworkColors: DEFAULT_BOOK_ARTWORK_COLORS,
          selectedAccentColorType: null,
          bookProgress: {
            currentChapterIndex: 0,
            currentChapterProgress: 0,
          },
          bookProgressValue: 0,
          lastPlayedAt: null,
          finishedAt: null,
          hasAutoGeneratedChapters: false,
          metadata: {
            year: chapter.year,
            description: chapter.description,
            narrator: chapter.narrator,
            genre: chapter.genre,
            sampleRate: chapter.sampleRate,
            bitrate: chapter.bitrate,
            copyright: chapter.copyright,
            codec: chapter.codec,
            totalTrackCount: chapter.totalTrackCount,
            // Tags off the file. First file wins, same as bitrate/codec above.
            series: chapter.series,
            part: chapter.part,
            grouping: chapter.grouping,
            fileFormat: chapter.fileFormat,
            // Called here, inside the branch, and nowhere else — that is the
            // whole saving: every other file's thunk is dropped unevaluated.
            // A forgotten `()` type-checks (see `DeferredTagBlob`), which is
            // why a test pins the stored value's TYPE and not just its text.
            rawTagsJson: chapter.rawTagsJson?.(),
            ctime: chapter.ctime,
            mtime: chapter.mtime || null,
            // Scan-state only (not persisted): tells applyCueChaptersToBooks
            // to leave this book alone — its chapters came from MediaInfo.
            fromEmbeddedChapters: chapter.fromEmbeddedChapters === true,
          },
        },
      });
    }

    const entry = bookMap.get(bookKey)!;
    const chapterData: Chapter = {
      author: chapter.author,
      bookTitle: chapter.bookTitle,
      chapterTitle: chapter.chapterTitle,
      chapterNumber: chapter.chapterNumber,
      chapterDuration: chapter.chapterDuration,
      startMs: chapter.startMs,
      url: chapter.url,
      isAutoGenerated: false,
    };

    entry.book.chapters.push(chapterData);
    entry.book.bookDuration += chapterData.chapterDuration;
  }

  // Sort chapters within each book by chapter number and determine isSingleFile
  for (const entry of bookMap.values()) {
    if (entry.book.chapters.length > 1) {
      entry.book.chapters.sort((a, b) => a.chapterNumber - b.chapterNumber);
    }

    // Determine if this is a single-file book (all chapters have the same URL)
    const chapters = entry.book.chapters;
    entry.book.isSingleFile =
      chapters.length > 0 &&
      chapters.every((c) => c.url === chapters[0].url);
  }

  return Array.from(bookMap.values());
}
