/**
 * Chapter rows whose QUEUE SHAPE is unambiguous, for tests that used to signal
 * the shape with a queue length.
 *
 * ⚠ A CHAPTER ROW CARRYING ONLY `startMs` IS NOT SHAPE-NEUTRAL — it reads as
 * MULTI-ITEM, and that is the trap these fixtures exist to close. Sites that
 * ask `queueShapeOf` read `url`, `chapterDuration` and `isAutoGenerated` as
 * well, and rows missing them accidentally SATISFY the clipped-chapters gate:
 * every `url` is `undefined` so the rows read as one file, and an absent
 * `chapterDuration` estimates a zero-byte sample table that fits under any
 * heap budget. A fixture meaning "legacy single-file book" therefore answers
 * `'multi-item'` unless it says otherwise.
 *
 * Named for the Queue shape rather than for the Book on disk: CONTEXT.md's
 * **Queue shape** entry lists "single-file" under _Avoid_, because that
 * describes how the Book is stored and not how its Queue was built.
 */

/**
 * One file, chapters as absolute seek offsets → a ONE-ITEM Queue.
 *
 * The rows are auto-generated, and that is what does the work: the
 * auto-chapter exclusion in `shouldUseClippedChapters` keeps them off the
 * clipped path (synthetic boundaries have no seek point in the file), which
 * is the legacy shape without needing a book big enough to fail the memory
 * gate.
 */
export const oneItemChapters = (startMsList: number[]) =>
  startMsList.map((startMs) => ({
    startMs,
    url: '/book.mp3',
    chapterDuration: 600,
    isAutoGenerated: true,
  }));

/** One file per chapter → always a MULTI-ITEM Queue. */
export const multiItemChapters = (count: number) =>
  Array.from({ length: count }, (_, i) => ({
    startMs: 0,
    url: `/${i + 1}.mp3`,
    chapterDuration: 600,
    isAutoGenerated: false,
  }));
