/**
 * Generates `shims/lucideIcons.js` — the Metro alias for `lucide-react-native`.
 *
 * WHY: `lucide-react-native`'s barrel re-exports ~1,600 icons (3,276 modules).
 * Metro does not tree-shake, so importing one icon from the barrel bundles all
 * of them — measured at 1.3 MB, 16.2% of the production JS bundle, for the 67
 * icons this app actually uses. The generated shim re-exports only those 67 by
 * deep path, and `metro.config.js` aliases the package name to it. Measured
 * saving: 1.46 MB (18.6% of the bundle).
 *
 * The PascalCase -> filename mapping is read from lucide's OWN barrel rather
 * than derived by kebab-casing, because some exported names are renamed
 * aliases whose filenames do not follow from the name (`BarChart3` lives in
 * `chart-column.js`, `HelpCircle` in `circle-question-mark.js`). Kebab-casing
 * those produces paths that do not exist.
 *
 * Run after adding or removing a lucide import:
 *     npm run generate:lucide-shim
 *
 * `lucideShim.test.ts` fails if the committed shim is out of date, so drift is
 * caught by the suite rather than by an `undefined` component at render time.
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const SHIM_PATH = path.join(ROOT, 'shims/lucideIcons.js');
const PACKAGE = 'lucide-react-native';
const BARREL = path.join(
  ROOT,
  'node_modules/lucide-react-native/dist/esm/lucide-react-native.js',
);

/** Source files that could import icons: everything in `src/`, plus the entry. */
function sourceFiles() {
  const found = [];

  const walk = (dir) => {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      const full = path.join(dir, entry.name);
      // Tests are excluded: jest resolves the real package, not this alias.
      if (entry.isDirectory()) {
        if (entry.name !== '__tests__') walk(full);
      } else if (/\.(ts|tsx|js|jsx)$/.test(entry.name)) {
        found.push(full);
      }
    }
  };

  walk(path.join(ROOT, 'src'));
  found.push(path.join(ROOT, 'index.js'));
  return found;
}

/**
 * Names imported as VALUES from the package. Comments are stripped first: prose
 * mentioning an icon name inside a block comment otherwise reads as an import.
 */
function collectUsedNames() {
  const used = new Set();
  const importRe = new RegExp(
    `import\\s+(type\\s+)?\\{([^}]*)\\}\\s*from\\s*['"]${PACKAGE}['"]`,
    'g',
  );

  for (const file of sourceFiles()) {
    const source = fs
      .readFileSync(file, 'utf8')
      .replace(/\/\*[\s\S]*?\*\//g, '')
      .replace(/^\s*\/\/.*$/gm, '');

    for (const match of source.matchAll(importRe)) {
      if (match[1]) continue; // `import type { ... }` — erased at compile time.

      for (const raw of match[2].split(',')) {
        const specifier = raw.trim();
        if (!specifier || /^type\s/.test(specifier)) continue;
        used.add(specifier.split(/\s+as\s+/)[0].trim());
      }
    }
  }

  return used;
}

/** Exported name -> module path, straight from lucide's barrel. */
function buildNameToModule() {
  const barrel = fs.readFileSync(BARREL, 'utf8');
  const mapping = {};

  for (const match of barrel.matchAll(
    /export\s*\{([^}]*)\}\s*from\s*['"]\.\/(.*?)\.js['"]/g,
  )) {
    for (const raw of match[1].split(',')) {
      const named = raw.trim().match(/default as ([A-Za-z0-9_]+)/);
      if (named) mapping[named[1]] = match[2];
    }
  }

  return mapping;
}

function renderShim() {
  const mapping = buildNameToModule();
  // A used name absent from the barrel's value exports is a type (`LucideIcon`),
  // which erases at compile time and needs no runtime re-export.
  const icons = [...collectUsedNames()].filter((name) => mapping[name]).sort();

  const lines = icons.map(
    (name) =>
      `export { default as ${name} } from '${PACKAGE}/dist/esm/${mapping[name]}';`,
  );

  return [
    '// GENERATED by scripts/generateLucideShim.js — do not edit by hand.',
    '// Run `npm run generate:lucide-shim` after changing a lucide import.',
    '// Rationale lives in the generator; alias wiring lives in metro.config.js.',
    '',
    ...lines,
    '',
  ].join('\n');
}

/** The committed shim, as it currently sits on disk. */
function readShim() {
  return fs.readFileSync(SHIM_PATH, 'utf8');
}

module.exports = {
  renderShim,
  readShim,
  collectUsedNames,
  buildNameToModule,
  SHIM_PATH,
};

if (require.main === module) {
  const contents = renderShim();
  fs.mkdirSync(path.dirname(SHIM_PATH), { recursive: true });
  fs.writeFileSync(SHIM_PATH, contents);
  const count = contents.split('\n').filter((l) => l.startsWith('export ')).length;
  console.log(`Wrote ${path.relative(ROOT, SHIM_PATH)} (${count} icons)`);
}
